--Consultar un periodo cargado

DELETE FROM WEBSERV_PRES_SERV_COMP SP WHERE SP.ID_SECO IN (
SELECT SP.ID_SECO FROM WEBSERV_PRES_SERV_COMP SP 
join WEBSERV_PRES_PRES pp on PP.ID_PRES=SP.ID_PRES
where  pp.REPO_SERV_ID=:REPO_SERV_ID and pp.REPO_TIRE_ID=:REPO_TIRE_ID and pp.REPO_PERIODO BETWEEN :PERIODO_INICIAL AND :PERIODO_FINAL);

DELETE FROM WEBSERV_PRES_PROD_NUTR PN WHERE PN.ID_PRNU IN(
SELECT PN.ID_PRNU FROM WEBSERV_PRES_PROD_NUTR PN 
join WEBSERV_PRES_PRES pp on PP.ID_PRES=PN.ID_PRES
where  pp.REPO_SERV_ID=:REPO_SERV_ID and pp.REPO_TIRE_ID=:REPO_TIRE_ID and pp.REPO_PERIODO BETWEEN :PERIODO_INICIAL AND :PERIODO_FINAL);

DELETE FROM WEBSERV_PRES_DISP PD WHERE PD.ID_DISP IN (  
SELECT PD.ID_DISP FROM WEBSERV_PRES_DISP PD 
join WEBSERV_PRES_PRES pp on PP.ID_PRES=PD.ID_PRES
where  pp.REPO_SERV_ID=:REPO_SERV_ID and pp.REPO_TIRE_ID=:REPO_TIRE_ID and pp.REPO_PERIODO BETWEEN :PERIODO_INICIAL AND :PERIODO_FINAL);

DELETE FROM WEBSERV_PRES_PROC PPR WHERE PPR.ID_PROC IN ( 
SELECT PPR.ID_PROC FROM WEBSERV_PRES_PROC PPR 
join WEBSERV_PRES_PRES pp on PP.ID_PRES=PPR.ID_PRES
where  pp.REPO_SERV_ID=:REPO_SERV_ID and pp.REPO_TIRE_ID=:REPO_TIRE_ID and pp.REPO_PERIODO BETWEEN :PERIODO_INICIAL AND :PERIODO_FINAL);

--Medicamentos
DELETE FROM WEBSERV_PRES_INDI_UNIRS IU WHERE IU.ID_IMUN IN(
SELECT IU.ID_IMUN FROM WEBSERV_PRES_INDI_UNIRS IU 
JOIN WEBSERV_PRES_MEDI PM ON PM.ID_MEDI=IU.ID_MEDI
JOIN WEBSERV_PRES_PRES pp on PP.ID_PRES=PM.ID_PRES
where  pp.REPO_SERV_ID=:REPO_SERV_ID and pp.REPO_TIRE_ID=:REPO_TIRE_ID and pp.REPO_PERIODO BETWEEN :PERIODO_INICIAL AND :PERIODO_FINAL);

DELETE FROM WEBSERV_PRES_PRIN_ACTI PPA WHERE PPA.ID_PRAC IN (
SELECT PPA.ID_PRAC FROM WEBSERV_PRES_PRIN_ACTI PPA
JOIN WEBSERV_PRES_MEDI PM ON PM.ID_MEDI=PPA.ID_MEDI
JOIN WEBSERV_PRES_PRES pp on PP.ID_PRES=PM.ID_PRES
where  pp.REPO_SERV_ID=:REPO_SERV_ID and pp.REPO_TIRE_ID=:REPO_TIRE_ID and pp.REPO_PERIODO BETWEEN :PERIODO_INICIAL AND :PERIODO_FINAL);

DELETE  FROM WEBSERV_PRES_MEDI PM WHERE PM.ID_MEDI IN(
SELECT PM.ID_MEDI FROM WEBSERV_PRES_MEDI PM 
join WEBSERV_PRES_PRES pp on PP.ID_PRES=PM.ID_PRES
where  pp.REPO_SERV_ID=:REPO_SERV_ID and pp.REPO_TIRE_ID=:REPO_TIRE_ID and pp.REPO_PERIODO BETWEEN :PERIODO_INICIAL AND :PERIODO_FINAL);

--Medicamentos

DELETE FROM WEBSERV_PRES_PRES where id_pres in(
SELECT PP.ID_PRES FROM WEBSERV_PRES_PRES PP 
where  pp.REPO_SERV_ID=:REPO_SERV_ID and pp.REPO_TIRE_ID=:REPO_TIRE_ID and pp.REPO_PERIODO BETWEEN :PERIODO_INICIAL AND :PERIODO_FINAL);

DELETE FROM WEBSERV_REPORTES_JSON RJ
where  RJ.SERV_ID=:REPO_SERV_ID and RJ.TIRE_ID=:REPO_TIRE_ID and RJ.PERIODO BETWEEN :PERIODO_INICIAL AND :PERIODO_FINAL;





/* Fatal error: Allowed memory size of 536870912 bytes exhausted (CORREGIDO)
2019-02-14
2019-05-16
2019-07-22
2019-08-22
2019-08-29
2019-09-02
2019-09-20
2019-09-27
2019-10-26
2019-11-06
2019-11-09
2019-11-27
2019-12-18

*/


/* Warning: oci_parse(): ORA-01756: la cadena entrecomillada no esta terminada correctamente
2019-06-07(medicamentos)
2019-07-22(Servcion complementario)
2019-08-20(productos nutricionales)2445
2019-10-25(productos nutricionales)2445
*/

