
--Municipios
select * from  GEOGRAPHICLOCATION
where parent>'2';


--departamentos
select * from  GEOGRAPHICLOCATION
where parent='1'
AND "Level"='2';


----Departamento y municipi de los afiliados
SELECT B.ESTADO,B.TIDPODOCUMENTO,B.DOCUMENTO, B.DEPARTAMENTO, B.MUNICIPIO,B.NOM_MPIO,B.NOM_DPTO,B.MES, B.*
FROM ZZZ_BDUAHISSUB@PDBLCSTBY01 B 
WHERE B.MES IN (SELECT MAX(MES) FROM ZZZ_BDUAHISSUB@PDBLCSTBY01);

select * FROM ZZZ_BDUAHISSUB@PDBLCSTBY01 B 
where b.DOCUMENTO ='77183570'

--