SELECT 
PD.ID_DISP,
PD.ID_PRES,
PP.NOPRESCRIPCION,
PD.CONORDEN,

DECODE(PD.TIPOPREST,NULL,'NO EXISTE',PD.TIPOPREST)TIPOPREST,--7.Lista(Medi-TipoPrest)
DECODE( TP.DESCRIPCION,NULL,'NO EXISTE', TP.DESCRIPCION) AS DESC_TIPOPREST,

DECODE(PD.CAUSAS1,0,'NO',1,'SI',NULL,'NO EXISTE',PD.CAUSAS1)CAUSAS1,--2. Lista(Presc-Si-NO)

DECODE(PD.CODDISP,NULL,'NO EXISTE',PD.CODDISP)CODDISP,--17.Lista(Tipos disp médi)
DECODE(TM.DESCRIPCION,NULL,'NO EXISTE',TM.DESCRIPCION)DESC_CODDISP,
DECODE(PD.CANFORM,NULL,'NO EXISTE',PD.CANFORM)CANFORM,
DECODE(PD.CADAFREUSO,NULL,'NO EXISTE',PD.CADAFREUSO)CADAFREUSO,
DECODE(PD.CODFREUSO,NULL,'NO EXISTE',PD.CODFREUSO)CODFREUSO,--11. Lista(Medi-CodFreAdmon)
DECODE(PD.CANT,NULL,'NO EXISTE',PD.CANT)CANT,

DECODE(PD.CODPERDURTRAT,NULL,'NO EXISTE',PD.CODPERDURTRAT)CODPERDURTRAT,--11. Lista(Medi-CodFreAdmon)
DECODE(PDU.DESCRIPCION,NULL,'NO EXISTE',PDU.DESCRIPCION) AS DESC_CODPERDURTRAT,

DECODE(PD.CANTTOTAL,NULL,'NO EXISTE',PD.CANTTOTAL)CANTTOTAL,
DECODE(PD.JUSTNOPBS,NULL,'NO EXISTE',PD.JUSTNOPBS)JUSTNOPBS,
DECODE(PD.INDREC,NULL,'NO EXISTE',PD.INDREC)INDREC,

DECODE(PD.ESTJM,NULL,'NO EXISTE',PD.ESTJM)ESTJM,--14. Lista (Medi-EstJM)
DECODE(EJ.DESCRIPCION,NULL,'NO EXISTE',EJ.DESCRIPCION) AS DESC_ESTJM

FROM WEBSERV_PRES_DISP PD
LEFT JOIN WEBSERV_PRES_PRES PP ON PD.ID_PRES=PP.ID_PRES
LEFT JOIN WEBSERV_REF_PRE_TI_PR   TP ON PD.TIPOPREST=  TP.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TD_ME TM ON PD.CODDISP=TM.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS PDU ON PD.CODPERDURTRAT=PDU.CODIGO
LEFT JOIN WEBSERV_REF_PRE_ES_JP   EJ ON PD.ESTJM=EJ.CODIGO;



/*Columnas y sus descrtipciones
ID_DISP,
ID_PRES,
CONORDEN,
TIPOPREST,--7.Lista(Medi-TipoPrest)
CAUSAS1,--2. Lista(Presc-Si-NO)
CODDISP,--17.Lista(Tipos disp médi)
CANFORM,
CADAFREUSO,
CODFREUSO,--11. Lista(Medi-CodFreAdmon)
CANT,
CODPERDURTRAT,--11. Lista(Medi-CodFreAdmon)
CANTTOTAL,
JUSTNOPBS,
INDREC,
ESTJM----14. Lista (Medi-EstJM)
*/