--medicamentos
SELECT 
  ID_MEDI,
  PP.NOPRESCRIPCION,
  CONORDEN,
  
  DECODE(TIPOMED,NULL,'NO EXISTE',TIPOMED) AS TIPOMED,  --6.Lista(Medi-TipoMed)
  DECODE(DBMS_LOB.SUBSTR(TM.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(TM.DESCRIPCION)) AS DESC_TIPOMED,
  
  DECODE(TIPOPREST,NULL,'NO EXISTE',TIPOPREST) AS TIPOPREST,--7.Lista(Medi-TipoPrest)
  DECODE(DBMS_LOB.SUBSTR( TP.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR( TP.DESCRIPCION)) AS DESC_TIPOPREST,
  
  CAUSAS1,  --2. Lista(Si-NO)
  DECODE(CAUSAS1,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS1,
  
  CAUSAS2,--2. Lista(Si-NO)
  DECODE(CAUSAS2,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS2,
  
  CAUSAS3,--2. Lista(Si-NO)
  DECODE(CAUSAS3,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS3,
  
  MEDPBSUTILIZADO,
  RZNCAUSAS31,
  DESCRZN31,
  
  RZNCAUSAS32,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS32,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS32,
  
  DESCRZN32,
  CAUSAS4,--2. Lista(Si-NO)
  DECODE(CAUSAS4,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS4,
  
  MEDPBSDESCARTADO,
  
  RZNCAUSAS41,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS41,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS41,
  
  DESCRZN41,
  
  RZNCAUSAS42,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS42,0,'NO',1,'SI','NO EXISTE') DESC_RZNCAUSAS42,
  
  DESCRZN42,
  
  RZNCAUSAS43,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS43,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS43,
  
  DESCRZN43,
  
  RZNCAUSAS44,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS44,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS44,
  
  DESCRZN44,
  
  CAUSAS5,   --2. Lista(Si-NO)
  DECODE(CAUSAS5,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS5,
  
  RZNCAUSAS5,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS5,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS5,
  
  CAUSAS6,   --2. Lista(Si-NO)
  DECODE(CAUSAS6,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS6,
  
  DESCMEDPRINACT,
  
  CODFF,--8. Lista(Medi-Form farmacéu)
  DECODE(DBMS_LOB.SUBSTR(FF.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(FF.DESCRIPCION)) AS DESC_CODFF,
  
  CODVA,--9. Lista(Vías de admin)
  DECODE(DBMS_LOB.SUBSTR(VA.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(VA.DESCRIPCION))DESC_CODVA,
  JUSTNOPBS,
  DOSIS,
  
  DOSISUM,--10. Lista(Medi-Unid medi)
  DECODE(DBMS_LOB.SUBSTR( UM.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR( UM.DESCRIPCION)) AS DESC_DOSISUM,
  DECODE(DBMS_LOB.SUBSTR( UM.DESCRIPCION2),NULL,'NO EXISTE',DBMS_LOB.SUBSTR( UM.DESCRIPCION2)) AS DESC_DOSISUM2,
  
  
  NOFADMON,
  
  CODFREADMON,--11. Lista(Medi-CodFreAdmon)
  DECODE(DBMS_LOB.SUBSTR(FA.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(FA.DESCRIPCION)) AS DESC_CODFREADMON,
  
  INDESP,     --12. Lista(Medi-IndEsp)  --Indicaciones Especiales
  DECODE(DBMS_LOB.SUBSTR(IE.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(IE.DESCRIPCION)) AS DESC_INDESP,
  CANTRAT,
  
  DURTRAT,--11. Lista(Medi-DurTrat )
  DECODE(DBMS_LOB.SUBSTR(DT.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(DT.DESCRIPCION)) AS DESC_DURTRAT,
  
  CANTTOTALF,
  
  /*concadenar el codigo y la descripcion en el mismo campo*/UFCANTTOTAL,--13. Lista(Medi-Presentación)
  DECODE(DBMS_LOB.SUBSTR(UC.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(UC.DESCRIPCION)) AS DESC_UFCANTTOTAL,
  
  INDREC,
  ESTJM,--14. Lista (Medi-EstJM)
  DECODE(DBMS_LOB.SUBSTR(EJ.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(EJ.DESCRIPCION)) AS DESC_ESTJM
FROM WEBSERV_PRES_MEDI pm
LEFT JOIN WEBSERV_PRES_PRES       PP ON PM.ID_PRES=    PP.ID_PRES
LEFT JOIN WEBSERV_REF_PRE_TI_ME   TM ON PM.TIPOMED=    TM.CODIGO 
LEFT JOIN WEBSERV_REF_PRE_TI_PR   TP ON PM.TIPOPREST=  TP.CODIGO
LEFT JOIN WEBSERV_REF_PRE_FO_FA   FF ON PM.CODFF=      FF.CODIGO
LEFT JOIN WEBSERV_REF_PRE_VI_AD   VA ON PM.CODVA=      VA.CODIGO
LEFT JOIN WEBSERV_REF_PRE_UN_ME   UM ON PM.DOSISUM=    UM.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS FA ON PM.CODFREADMON=FA.CODIGO
LEFT JOIN WEBSERV_REF_PRE_IN_ES   IE ON PM.INDESP=     IE.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS DT ON PM.DURTRAT=    DT.CODIGO
LEFT JOIN WEBSERV_REF_PRE_UF_CT   UC ON PM.UFCANTTOTAL=UC.CODIGO
LEFT JOIN WEBSERV_REF_PRE_ES_JP   EJ ON PM.ESTJM=EJ.CODIGO
where  pp.REPO_SERV_ID=3 and pp.REPO_TISE_ID=2 and pp.REPO_PERIODO='01/01/2020';