--medicamentos
SELECT 
  ID_MEDI,
  PP.NOPRESCRIPCION,
  DECODE(CONORDEN, NULL,'NO EXISTE',CONORDEN) CONORDEN,
  
  DECODE(TIPOMED,NULL,'NO EXISTE',TIPOMED) AS TIPOMED,  --6.Lista(Medi-TipoMed)
  DECODE(TM.DESCRIPCION,NULL,'NO EXISTE',DBMS_LOB.SUBSTR(TM.DESCRIPCION)) AS DESC_TIPOMED,
  
  DECODE(TIPOPREST,NULL,'NO EXISTE',TIPOPREST) AS TIPOPREST,--7.Lista(Medi-TipoPrest)
  DECODE(DBMS_LOB.SUBSTR( TP.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR( TP.DESCRIPCION)) AS DESC_TIPOPREST,
  
  DECODE(CAUSAS1, NULL,'NO EXISTE',CAUSAS1) CAUSAS1,  --2. Lista(Si-NO)
  DECODE(CAUSAS1,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS1,
  
  DECODE(CAUSAS2, NULL,'NO EXISTE',CAUSAS2) CAUSAS2,--2. Lista(Si-NO)
  DECODE(CAUSAS2,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS2,
  
  DECODE(CAUSAS3, NULL,'NO EXISTE',CAUSAS3) CAUSAS3,--2. Lista(Si-NO)
  DECODE(CAUSAS3,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS3,
  
  DECODE(MEDPBSUTILIZADO, NULL,'NO EXISTE',MEDPBSUTILIZADO) MEDPBSUTILIZADO,
  
  DECODE(RZNCAUSAS31, NULL,'NO EXISTE',RZNCAUSAS31) RZNCAUSAS31,
  DECODE(RZNCAUSAS31,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS31, 
    
  DECODE(DESCRZN31, NULL,'NO EXISTE',DESCRZN31) DESCRZN31,
  
  DECODE(RZNCAUSAS32, NULL,'NO EXISTE',RZNCAUSAS32) RZNCAUSAS32,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS32,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS32,
  
  DECODE(DESCRZN32, NULL,'NO EXISTE',DESCRZN32) DESCRZN32,
  
  DECODE(CAUSAS4, NULL,'NO EXISTE',CAUSAS4) CAUSAS4,--2. Lista(Si-NO)
  DECODE(CAUSAS4,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS4,
  
  DECODE(MEDPBSDESCARTADO, NULL,'NO EXISTE',MEDPBSDESCARTADO) MEDPBSDESCARTADO,
  
  DECODE(RZNCAUSAS41, NULL,'NO EXISTE',RZNCAUSAS41) RZNCAUSAS41,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS41,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS41,
  
  DECODE(DESCRZN41, NULL,'NO EXISTE',DESCRZN41) DESCRZN41,
  
  DECODE(RZNCAUSAS42, NULL,'NO EXISTE',RZNCAUSAS42) RZNCAUSAS42,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS42,0,'NO',1,'SI','NO EXISTE') DESC_RZNCAUSAS42,
  
  DECODE(DESCRZN42, NULL,'NO EXISTE',DESCRZN42) DESCRZN42,
  
  DECODE(RZNCAUSAS43, NULL,'NO EXISTE',RZNCAUSAS43) RZNCAUSAS43,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS43,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS43,
  
  DECODE(DESCRZN43, NULL,'NO EXISTE',DESCRZN43) DESCRZN43,
  
  DECODE(RZNCAUSAS44, NULL,'NO EXISTE',RZNCAUSAS44) RZNCAUSAS44,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS44,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS44,
  
  DECODE(DESCRZN44, NULL,'NO EXISTE',DESCRZN44) DESCRZN44,
  
  DECODE(CAUSAS5, NULL,'NO EXISTE',CAUSAS5) CAUSAS5,   --2. Lista(Si-NO)
  DECODE(CAUSAS5,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS5,
  
  DECODE(RZNCAUSAS5, NULL,'NO EXISTE',RZNCAUSAS5) RZNCAUSAS5,--2. Lista(Si-NO)
  DECODE(RZNCAUSAS5,0,'NO',1,'SI','NO EXISTE') AS DESC_RZNCAUSAS5,
  
  DECODE(CAUSAS6, NULL,'NO EXISTE',CAUSAS6) CAUSAS6,   --2. Lista(Si-NO)
  DECODE(CAUSAS6,0,'NO',1,'SI','NO EXISTE') AS DESC_CAUSAS6,
  
  DECODE(DBMS_LOB.SUBSTR(DESCMEDPRINACT), NULL,'NO EXISTE',DBMS_LOB.SUBSTR(DESCMEDPRINACT)) DESCMEDPRINACT,
    
  DECODE(CODFF, NULL,'NO EXISTE',CODFF) CODFF,--8. Lista(Medi-Form farmacéu)
  DECODE(FF.DESCRIPCION,NULL,'NO EXISTE',FF.DESCRIPCION) AS DESC_CODFF,
  
  DECODE(CODVA, NULL,'NO EXISTE',CODVA) CODVA,--9. Lista(Vías de admin)
  DECODE(VA.DESCRIPCION,NULL,'NO EXISTE',VA.DESCRIPCION)DESC_CODVA,
  
  DECODE(JUSTNOPBS, NULL,'NO EXISTE',JUSTNOPBS) JUSTNOPBS,
  DECODE(DOSIS, NULL,'NO EXISTE',DOSIS) DOSIS,
  
  DECODE(DOSISUM, NULL,'NO EXISTE',DOSISUM) DOSISUM,--10. Lista(Medi-Unid medi)
  DECODE(DBMS_LOB.SUBSTR( UM.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR( UM.DESCRIPCION)) AS DESC_DOSISUM,
  DECODE(DBMS_LOB.SUBSTR( UM.DESCRIPCION2),NULL,'NO EXISTE',DBMS_LOB.SUBSTR( UM.DESCRIPCION2)) AS DESC_DOSISUM2,
  
  
  DECODE(NOFADMON, NULL,'NO EXISTE',NOFADMON) NOFADMON,
  
  DECODE(CODFREADMON, NULL,'NO EXISTE',CODFREADMON) CODFREADMON,--11. Lista(Medi-CodFreAdmon)
  DECODE(DBMS_LOB.SUBSTR(FA.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(FA.DESCRIPCION)) AS DESC_CODFREADMON,
  
  DECODE(INDESP, NULL,'NO EXISTE',INDESP) INDESP,     --12. Lista(Medi-IndEsp)  Indicaciones Especiales
  DECODE(DBMS_LOB.SUBSTR(IE.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(IE.DESCRIPCION)) AS DESC_INDESP,
  DECODE(CANTRAT, NULL,'NO EXISTE',CANTRAT) CANTRAT,
  
  DECODE(DURTRAT, NULL,'NO EXISTE',DURTRAT) DURTRAT,--11. Lista(Medi-DurTrat )
  DECODE(DBMS_LOB.SUBSTR(DT.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(DT.DESCRIPCION)) AS DESC_DURTRAT,
  
  DECODE(CANTTOTALF, NULL,'NO EXISTE',CANTTOTALF) CANTTOTALF,
  
  DECODE(UFCANTTOTAL, NULL,'NO EXISTE',UFCANTTOTAL) UFCANTTOTAL,--13. Lista(Medi-Presentación)
  DECODE(DBMS_LOB.SUBSTR(UC.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(UC.DESCRIPCION)) AS DESC_UFCANTTOTAL,
  
  DECODE(INDREC, NULL,'NO EXISTE',INDREC) INDREC,
  
  DECODE(ESTJM, NULL,'NO EXISTE',ESTJM) ESTJM,--14. Lista (Medi-EstJM)
  DECODE(EJ.DESCRIPCION,NULL,'NO EXISTE',EJ.DESCRIPCION) AS DESC_ESTJM
  
FROM WEBSERV_PRES_MEDI pm
LEFT JOIN WEBSERV_PRES_PRES       PP ON PM.ID_PRES=    PP.ID_PRES
LEFT JOIN WEBSERV_REF_PRE_TI_ME   TM ON PM.TIPOMED=    TM.CODIGO 
LEFT JOIN WEBSERV_REF_PRE_TI_PR   TP ON PM.TIPOPREST=  TP.CODIGO
LEFT JOIN WEBSERV_REF_PRE_FO_FA   FF ON PM.CODFF=      FF.CODIGO
LEFT JOIN WEBSERV_REF_PRE_VI_AD   VA ON PM.CODVA=      VA.CODIGO
LEFT JOIN WEBSERV_REF_PRE_UN_ME   UM ON PM.DOSISUM=    UM.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS FA ON PM.CODFREADMON=FA.CODIGO
LEFT JOIN WEBSERV_REF_PRE_IN_ES   IE ON PM.INDESP=     IE.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS DT ON PM.DURTRAT=    DT.CODIGO
LEFT JOIN WEBSERV_REF_PRE_UF_CT   UC ON PM.UFCANTTOTAL=UC.CODIGO
LEFT JOIN WEBSERV_REF_PRE_ES_JP   EJ ON PM.ESTJM=EJ.CODIGO
where  pp.REPO_SERV_ID=3 and pp.REPO_TISE_ID=2 and pp.REPO_PERIODO BETWEEN '01/01/2019' AND '05/01/2019';





/*Columnas con sus conversiones


*/