SELECT 
PP.NOPRESCRIPCION,
PIU.ID_MEDI,
DECODE(PIU.CONORDEN, NULL,'NO EXISTE',PIU.CONORDEN) CONORDEN,
DECODE(PIU.CODINDICACION, NULL,'NO EXISTE',PIU.CODINDICACION) CODINDICACION, 
DECODE(FIU.DESCRIPCION, NULL,'NO EXISTE',FIU.DESCRIPCION) DESC_CODINDICACION
FROM WEBSERV_PRES_INDI_UNIRS PIU
LEFT JOIN WEBSERV_REF_PRE_IND_UNI FIU ON PIU.CODINDICACION=FIU.CODIGO
LEFT JOIN WEBSERV_PRES_MEDI PM ON PIU.ID_MEDI=PM.ID_MEDI
LEFT JOIN WEBSERV_PRES_PRES PP ON PM.ID_PRES=PP.ID_PRES
where  pp.REPO_SERV_ID=3 and pp.REPO_TISE_ID=2 and pp.REPO_PERIODO BETWEEN '01/01/2020' AND '16/01/2020';