select 
PPR.ID_PROC,
PPR.ID_PRES,
PP.NOPRESCRIPCION,
DECODE(PPR.CONORDEN,NULL,'NO EXISTE',PPR.CONORDEN) CONORDEN,
DECODE(PPR.TIPOPREST,NULL,'NO EXISTE',PPR.TIPOPREST)TIPOPREST,--7.Lista(Medi-TipoPrest)
DECODE(TP.DESCRIPCION,NULL,'NO EXISTE',TP.DESCRIPCION) DESC_TIPOPREST,
DECODE(PPR.CAUSAS11,0,'NO',1,'SI','NO EXISTE')CAUSAS11,--2. Lista(Presc-Si-NO)
DECODE(PPR.CAUSAS12,0,'NO',1,'SI','NO EXISTE')CAUSAS12,--2. Lista(Presc-Si-NO)
DECODE(PPR.CAUSAS2,0,'NO',1,'SI','NO EXISTE') CAUSAS2,--2. Lista(Presc-Si-NO)
DECODE(PPR.CAUSAS3,0,'NO',1,'SI','NO EXISTE') CAUSAS3,--2. Lista(Presc-Si-NO)
DECODE(PPR.CAUSAS4,0,'NO',1,'SI','NO EXISTE') CAUSAS4,--2. Lista(Presc-Si-NO)

DECODE(PPR.PROPBSUTILIZADO,NULL,'NO EXISTE',PPR.PROPBSUTILIZADO) PROPBSUTILIZADO,--16. Lista(CUPS)
DECODE(CPU.DESCRIPCION,NULL,'NO EXISTE',CPU.DESCRIPCION) DESC_PROPBSUTILIZADO,

DECODE (PPR.CAUSAS5,0,'NO',1,'SI',NULL,'NO EXISTE',PPR.CAUSAS5)CAUSAS5,--2. Lista(Presc-Si-NO)

DECODE(PPR.PROPBSDESCARTADO, NULL,'NO EXISTE',PPR.PROPBSDESCARTADO)PROPBSDESCARTADO,--16. Lista(CUPS)
DECODE(CPD.DESCRIPCION,NULL,'NO EXISTE',CPD.DESCRIPCION)DESC_PROPBSDESCARTADO,

DECODE (PPR.RZNCAUSAS51,0,'NO',1,'SI',NULL,'NO EXISTE',PPR.RZNCAUSAS51) RZNCAUSAS51,--2. Lista(Presc-Si-NO)
DECODE(PPR.DESCRZN51,NULL,'NO EXISTE',PPR.DESCRZN51)DESCRZN51,
DECODE (PPR.RZNCAUSAS52,0,'NO',1,'SI',NULL,'NO EXISTE',PPR.RZNCAUSAS52) RZNCAUSAS52,--2. Lista(Presc-Si-NO)
DECODE(PPR.DESCRZN52,NULL,'NO EXISTE',PPR.DESCRZN52)DESCRZN52,
DECODE (PPR.CAUSAS6,0,'NO',1,'SI',NULL,'NO EXISTE',PPR.CAUSAS6) CAUSAS6,--2. Lista(Presc-Si-NO)
DECODE (PPR.CAUSAS7,0,'NO',1,'SI',NULL,'NO EXISTE',PPR.CAUSAS7) CAUSAS7,--2. Lista(Presc-Si-NO)

DECODE (PPR.CODCUPS,NULL,'NO EXISTE',PPR.CODCUPS)CODCUPS,--16. Lista(CUPS)
DECODE(CP.DESCRIPCION,NULL,'NO EXISTE',CP.DESCRIPCION)DESC_CODCUPS,


DECODE(PPR.CANFORM,NULL,'NO EXISTE',PPR.CANFORM)CANFORM,
DECODE(PPR.CADAFREUSO,NULL,'NO EXISTE',PPR.CADAFREUSO) CADAFREUSO,

DECODE(PPR.CODFREUSO,NULL,'NO EXISTE',PPR.CODFREUSO)CODFREUSO,--11. Lista(Medi-CodFreAdmon)
DECODE(FU.DESCRIPCION,NULL,'NO EXISTE',FU.DESCRIPCION)DESC_CODFREUSO,

DECODE(PPR.CANT,NULL,'NO EXISTE',PPR.CANT) CANT,
DECODE(PPR.CANTTOTAL,NULL,'NO EXISTE',PPR.CANTTOTAL) CANTTOTAL,

DECODE(PPR.CODPERDURTRAT,NULL,'NO EXISTE',PPR.CODPERDURTRAT)CODPERDURTRAT,--11. Lista(Medi-CodFreAdmon)
DECODE(DT.DESCRIPCION,NULL,'NO EXISTE',DT.DESCRIPCION)DESC_CODPERDURTRAT,

DECODE(PPR.JUSTNOPBS,NULL,'NO EXISTE',PPR.JUSTNOPBS)JUSTNOPBS,
DECODE(PPR.INDREC,NULL,'NO EXISTE',PPR.INDREC) INDREC,

DECODE(PPR.ESTJM,NULL,'NO EXISTE',PPR.ESTJM)ESTJM,--14. Lista (Medi-EstJM)
DECODE(EJ.DESCRIPCION,NULL,'NO EXISTE',EJ.DESCRIPCION) DESC_ESTJM

from WEBSERV_PRES_PROC PPR
LEFT JOIN WEBSERV_PRES_PRES PP ON PP.ID_PRES=PPR.ID_PRES
LEFT JOIN WEBSERV_REF_PRE_TI_PR TP ON TP.CODIGO=PPR.TIPOPREST 
LEFT JOIN WEBSERV_REF_PRE_CUPS CPU ON CPU.CODIGO=PPR.PROPBSUTILIZADO
LEFT JOIN WEBSERV_REF_PRE_CUPS CPD ON CPD.CODIGO=PPR.PROPBSDESCARTADO  
LEFT JOIN WEBSERV_REF_PRE_CUPS CP ON CP.CODIGO=PPR.CODCUPS  
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS FU ON FU.CODIGO=PPR.CODFREUSO
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS DT ON DT.CODIGO=PPR.CODPERDURTRAT
LEFT JOIN WEBSERV_REF_PRE_ES_JP   EJ ON EJ.CODIGO=PPR.ESTJM
where  pp.REPO_SERV_ID=3 and pp.REPO_TISE_ID=2 and pp.REPO_PERIODO BETWEEN '01/01/2019' AND '16/01/2019';





/*Lista de columnas 
ID_PROC,
ID_PRES,
CONORDEN,
TIPOPREST,--7.Lista(Medi-TipoPrest)
CAUSAS11,--2. Lista(Presc-Si-NO)
CAUSAS12,--2. Lista(Presc-Si-NO)
CAUSAS2,--2. Lista(Presc-Si-NO)
CAUSAS3,--2. Lista(Presc-Si-NO)
CAUSAS4,--2. Lista(Presc-Si-NO)
PROPBSUTILIZADO,--16. Lista(CUPS)
CAUSAS5,--2. Lista(Presc-Si-NO)
PROPBSDESCARTADO,--16. Lista(CUPS)
RZNCAUSAS51,--2. Lista(Presc-Si-NO)
DESCRZN51,
RZNCAUSAS52,--2. Lista(Presc-Si-NO)
DESCRZN52,
CAUSAS6,--2. Lista(Presc-Si-NO)
CAUSAS7,--2. Lista(Presc-Si-NO)
CODCUPS,--16. Lista(CUPS)
CANFORM,
CADAFREUSO,
CODFREUSO,--11. Lista(Medi-CodFreAdmon)
CANT,
CANTTOTAL,
CODPERDURTRAT,--11. Lista(Medi-CodFreAdmon)
JUSTNOPBS,
INDREC,
ESTJM--14. Lista (Medi-EstJM)
*/