select 
PPN.ID_PRNU,
PPN.ID_PRES,
PP.NOPRESCRIPCION,
PPN.CONORDEN,
DECODE(PPN.TIPOPREST,NULL,'NO EXISTE',PPN.TIPOPREST)TIPOPREST,--7.Lista(Medi-TipoPrest)
DECODE(TP.DESCRIPCION,NULL,'NO EXISTE',TP.DESCRIPCION) DESC_TIPOPREST,

DECODE(PPN.CAUSAS1,0,'NO',1,'SI',NULL,'NO EXISTE',PPN.CAUSAS1) CAUSAS1,--2. Lista(Presc-Si-NO)
DECODE(PPN.CAUSAS2,0,'NO',1,'SI',NULL,'NO EXISTE',PPN.CAUSAS2)CAUSAS2,--2. Lista(Presc-Si-NO
DECODE(PPN.CAUSAS3,0,'NO',1,'SI',NULL,'NO EXISTE',PPN.CAUSAS3)CAUSAS3,--2. Lista(Presc-Si-NO
DECODE(PPN.CAUSAS4,0,'NO',1,'SI',NULL,'NO EXISTE',PPN.CAUSAS4)CAUSAS4,--2. Lista(Presc-Si-NO
DECODE(PPN.PRONUTUTILIZADO,NULL,'NO EXISTE',PPN.PRONUTUTILIZADO)PRONUTUTILIZADO,
DECODE(PPN.RZNCAUSAS41,0,'NO',1,'SI',NULL,'NO EXISTE',PPN.RZNCAUSAS41)RZNCAUSAS41,--2. Lista(Presc-Si-NO
DECODE(PPN.DESCRZN41,NULL,'NO EXISTE',PPN.DESCRZN41)DESCRZN41,
DECODE(PPN.RZNCAUSAS42,0,'NO',1,'SI',NULL,'NO EXISTE',PPN.RZNCAUSAS42)RZNCAUSAS42,--2. Lista(Presc-Si-NO
DECODE(PPN.DESCRZN42,NULL,'NO EXISTE',PPN.DESCRZN42)DESCRZN42,
DECODE(PPN.CAUSAS5,0,'NO',1,'SI',NULL,'NO EXISTE',PPN.CAUSAS5)CAUSAS5,--2. Lista(Presc-Si-NO
DECODE(PPN.PRONUTDESCARTADO,NULL,'NO EXISTE',PPN.PRONUTDESCARTADO)PRONUTDESCARTADO,
DECODE(PPN.RZNCAUSAS51,NULL,'NO EXISTE',PPN.RZNCAUSAS51)RZNCAUSAS51,--2. Lista(Presc-Si-NO
DECODE(PPN.DESCRZN51,NULL,'NO EXISTE',PPN.DESCRZN51)DESCRZN51,
DECODE(PPN.RZNCAUSAS52,0,'NO',1,'SI',NULL,'NO EXISTE',PPN.RZNCAUSAS52)RZNCAUSAS52,--2. Lista(Presc-Si-NO
DECODE(PPN.DESCRZN52,NULL,'NO EXISTE',PPN.DESCRZN52)DESCRZN52,
DECODE(PPN.RZNCAUSAS53,0,'NO',1,'SI',NULL,'NO EXISTE',PPN.RZNCAUSAS53)RZNCAUSAS53,--2. Lista(Presc-Si-NO
DECODE(PPN.DESCRZN53,NULL,'NO EXISTE',PPN.DESCRZN53)DESCRZN53,
DECODE(PPN.RZNCAUSAS54,0,'NO',1,'SI',NULL,'NO EXISTE')RZNCAUSAS54,--2. Lista(Presc-Si-NO
DECODE(PPN.DESCRZN54,NULL,'NO EXISTE',PPN.DESCRZN54)DESCRZN54,

DECODE(PPN.DXENFHUER,NULL,'NO EXISTE',PPN.DXENFHUER)DXENFHUER,--18. Lista(Diagnostico)
DECODE(DXF.DESCRIPCION,NULL,'Sin Diagnóstico',DXF.DESCRIPCION)DESC_DXENFHUER,

DECODE(PPN.DXVIH,NULL,'NO EXISTE',PPN.DXVIH)DXVIH,--18. Lista(Diagnostico)
DECODE(DXV.DESCRIPCION,NULL,'Sin Diagnóstico',DXV.DESCRIPCION)DESC_DXVIH,

DECODE(PPN.DXCAPAL,NULL,'NO EXISTE',PPN.DXCAPAL)DXCAPAL,--18. Lista(Diagnostico)
DECODE(DXC.DESCRIPCION,NULL,'Sin Diagnóstico',DXC.DESCRIPCION)DESC_DXCAPAL,


DECODE(PPN.DXENFRCEV,NULL,'NO EXISTE',PPN.DXENFRCEV)DXENFRCEV,--18. Lista(Diagnostico)
DECODE(DXE.DESCRIPCION,NULL,'Sin Diagnóstico',DXE.DESCRIPCION) DESC_DXENFRCEV,


DECODE(PPN.DXDESPRO,NULL,'NO EXISTE',PPN.DXDESPRO)DXDESPRO,--18. Lista(Diagnostico)
DECODE(DXD.DESCRIPCION,NULL,'Sin Diagnóstico',DXD.DESCRIPCION)DESC_DXDESPRO,


DECODE(PPN.TIPPPRONUT,NULL,'NO EXISTE',PPN.TIPPPRONUT)TIPPPRONUT,--19. Lista(Tipos produ nutri)
DECODE(TN.DESCRIPCION,NULL,'NO EXISTE',TN.DESCRIPCION)DESC_TIPPPRONUT,

DECODE(PPN.DESCPRODNUTR,NULL,'NO EXISTE',PPN.DESCPRODNUTR)DESCPRODNUTR,--20.Lista(productos nutricion)
DECODE(PN.NOMBRE_COMERCIAL,NULL,'NO EXISTE',PN.NOMBRE_COMERCIAL)DESC_DESCPRODNUTR,
DECODE(PN.DESCR_GRUPO_NIVEL_1,NULL,'NO EXISTE',PN.DESCR_GRUPO_NIVEL_1)DESCR_GRUPO_NIVEL_1,
DECODE(PN.PRESENTACION_COMERCIAL,NULL,'NO EXISTE',PN.PRESENTACION_COMERCIAL)PRESENTACION_COMERCIAL,
DECODE(PN.UNIDADES,NULL,'NO EXISTE',PN.UNIDADES)UNIDADES,

DECODE(PPN.CODFORMA,NULL,'NO EXISTE',PPN.CODFORMA)CODFORMA,--21.Listas(Formas Product Nutri)
DECODE(FN.DESCRIPCION,NULL,'NO EXISTE',FN.DESCRIPCION)DESC_CODFORMA,

DECODE(PPN.CODVIAADMON,NULL,'NO EXISTE',PPN.CODVIAADMON)CODVIAADMON,--22. Listas(CodViaAdmon)
DECODE(VA.DESCRIPCION,NULL,'NO EXISTE',VA.DESCRIPCION)DESC_CODVIAADMON,

DECODE(PPN.JUSTNOPBS,NULL,'NO EXISTE',PPN.JUSTNOPBS)JUSTNOPBS,
DECODE(PPN.DOSIS,NULL,'NO EXISTE',PPN.DOSIS)DOSIS,

DECODE(PPN.DOSISUM,NULL,'NO EXISTE',PPN.DOSISUM)DOSISUM,--10. Lista(Medi-Unid medi)
DECODE(UM.DESCRIPCION,NULL,'NO EXISTE',UM.DESCRIPCION) AS DESC_DOSISUM,
DECODE(UM.DESCRIPCION2,NULL,'NO EXISTE',UM.DESCRIPCION2) AS DESC_DOSISUM2,
  
DECODE(PPN.NOFADMON,NULL,'NO EXISTE',PPN.NOFADMON)NOFADMON,

DECODE(PPN.CODFREADMON,NULL,'NO EXISTE',PPN.CODFREADMON)CODFREADMON,--11. Lista(Medi-CodFreAdmon)
DECODE(FA.DESCRIPCION,NULL,'NO EXISTE',FA.DESCRIPCION) AS DESC_CODFREADMON,
  
DECODE(PPN.INDESP,NULL,'NO EXISTE',PPN.INDESP)INDESP,
DECODE(PPN.CANTRAT,NULL,'NO EXISTE',PPN.CANTRAT)CANTRAT,

DECODE(PPN.DURTRAT,NULL,'NO EXISTE',PPN.DURTRAT) DURTRAT,--11. Lista(Medi-CodFreAdmon)
DECODE(DT.DESCRIPCION,NULL,'NO EXISTE',DT.DESCRIPCION) AS DESC_DURTRAT,

DECODE(PPN.CANTTOTALF,NULL,'NO EXISTE',PPN.CANTTOTALF)CANTTOTALF,

DECODE(PPN.UFCANTTOTAL,NULL,'NO EXISTE',PPN.UFCANTTOTAL)UFCANTTOTAL,--21.Listas(Formas Product Nutri)
DECODE(FCT.DESCRIPCION,NULL,'NO EXISTE',FCT.DESCRIPCION)DESC_UFCANTTOTAL,

DECODE(PPN.INDREC,NULL,'NO EXISTE',PPN.INDREC)INDREC,
DECODE(PPN.NOPRESCASO,NULL,'NO EXISTE',PPN.NOPRESCASO)NOPRESCASO,

DECODE(PPN.ESTJM,NULL,'NO EXISTE',PPN.ESTJM)ESTJM,--14. Lista (Medi-EstJM)
DECODE(EJ.DESCRIPCION,NULL,'NO EXISTE',EJ.DESCRIPCION) AS DESC_ESTJM

FROM WEBSERV_PRES_PROD_NUTR PPN
LEFT JOIN WEBSERV_PRES_PRES PP ON PP.ID_PRES=PPN.ID_PRES
LEFT JOIN WEBSERV_REF_PRE_TI_PR TP ON PPN.TIPOPREST=TP.CODIGO
LEFT JOIN WEBSERV_REF_PRE_DIAG DXF ON PPN.DXENFHUER=DXF.CODIGO
LEFT JOIN WEBSERV_REF_PRE_DIAG DXV ON PPN.DXVIH=DXV.CODIGO
LEFT JOIN WEBSERV_REF_PRE_DIAG DXC ON PPN.DXCAPAL=DXC.CODIGO
LEFT JOIN WEBSERV_REF_PRE_DIAG DXE ON PPN.DXENFRCEV=DXE.CODIGO
LEFT JOIN WEBSERV_REF_PRE_DIAG DXD ON PPN.DXDESPRO=DXD.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TP_NU TN ON PPN.TIPPPRONUT=TN.CODIGO
LEFT JOIN WEBSERV_REF_PRE_PR_NU PN ON PPN.DESCPRODNUTR=PN.CODIGO
LEFT JOIN WEBSERV_REF_PRE_FP_NU FN ON PPN.CODFORMA=FN.CODIGO
LEFT JOIN WEBSERV_REF_PRE_VA_PN VA ON PPN.CODVIAADMON=VA.CODIGO
LEFT JOIN WEBSERV_REF_PRE_UN_ME UM ON PPN.DOSISUM=    UM.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS FA ON PPN.CODFREADMON=FA.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS DT ON PPN.DURTRAT=    DT.CODIGO
LEFT JOIN WEBSERV_REF_PRE_FP_NU FCT ON PPN.UFCANTTOTAL=FCT.CODIGO
LEFT JOIN WEBSERV_REF_PRE_ES_JP   EJ ON PPN.ESTJM=EJ.CODIGO
WHERE PP.NOPRESCRIPCION='20200209163017348801';

/*
columnas con sus traducciones
ID_PRES,
CONORDEN,
TIPOPREST,--7.Lista(Medi-TipoPrest)
CAUSAS1,--2. Lista(Presc-Si-NO)
CAUSAS2,--2. Lista(Presc-Si-NO
CAUSAS3,--2. Lista(Presc-Si-NO
CAUSAS4,--2. Lista(Presc-Si-NO
PRONUTUTILIZADO,
RZNCAUSAS41,--2. Lista(Presc-Si-NO
DESCRZN41,
RZNCAUSAS42,--2. Lista(Presc-Si-NO
DESCRZN42,
CAUSAS5,--2. Lista(Presc-Si-NO
PRONUTDESCARTADO,
RZNCAUSAS51,--2. Lista(Presc-Si-NO
DESCRZN51,
RZNCAUSAS52,--2. Lista(Presc-Si-NO
DESCRZN52,
RZNCAUSAS53,--2. Lista(Presc-Si-NO
DESCRZN53,
RZNCAUSAS54,--2. Lista(Presc-Si-NO
DESCRZN54,
DXENFHUER,--18. Lista(Diagnostico)
DXVIH,--18. Lista(Diagnostico)
DXCAPAL,--18. Lista(Diagnostico)
DXENFRCEV,--18. Lista(Diagnostico)
DXDESPRO,--18. Lista(Diagnostico)
TIPPPRONUT,--19. Lista(Tipos produ nutri)
DESCPRODNUTR,--20.Lista(productos nutricion)
CODFORMA,--21.Listas(Formas Product Nutri)
CODVIAADMON,--22. Listas(CodViaAdmon)
JUSTNOPBS,
DOSIS,
DOSISUM,--10. Lista(Medi-Unid medi)
NOFADMON,
CODFREADMON,--11. Lista(Medi-CodFreAdmon)
INDESP,
CANTRAT,
DURTRAT,--11. Lista(Medi-CodFreAdmon)
CANTTOTALF,
UFCANTTOTAL,--21.Listas(Formas Product Nutri)
INDREC,
NOPRESCASO,
ESTJM----14. Lista (Medi-EstJM)
*/


