SELECT 
SC.ID_SECO,
SC.ID_PRES,
PP.NOPRESCRIPCION,
SC.CONORDEN,

DECODE(SC.TIPOPREST,NULL,'NO EXISTE',SC.TIPOPREST)TIPOPREST,--7.Lista(Medi-TipoPrest)
DECODE(DBMS_LOB.SUBSTR( TP.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR( TP.DESCRIPCION)) AS DESC_TIPOPREST,

DECODE(SC.CAUSAS1,0,'NO',1,'SI',NULL,'NO EXISTE',SC.CAUSAS1) CAUSAS1,--2. Lista(Presc-Si-NO)
DECODE(SC.CAUSAS2,0,'NO',1,'SI',NULL,'NO EXISTE',SC.CAUSAS2)CAUSAS2,--2. Lista(Presc-Si-NO
DECODE(SC.CAUSAS3,0,'NO',1,'SI',NULL,'NO EXISTE',SC.CAUSAS3)CAUSAS3,--2. Lista(Presc-Si-NO
DECODE(SC.CAUSAS4,0,'NO',1,'SI',NULL,'NO EXISTE',SC.CAUSAS4)CAUSAS4,--2. Lista(Presc-Si-NO
DECODE(SC.DESCCAUSAS4,NULL,'NO EXISTE',SC.DESCCAUSAS4)DESCCAUSAS4,
DECODE(SC.CAUSAS5,NULL,'NO EXISTE',SC.CAUSAS5)CAUSAS5,--2. Lista(Presc-Si-NO)

DECODE(SC.CODSERCOMP,NULL,'NO EXISTE',SC.CODSERCOMP)CODSERCOMP,--23. Listas(Serv complem PR)  --(MIPRES)17. Listas Servicios complementarios PR
DECODE(SP.DESCRIPCION,NULL,'NO EXISTE',SP.DESCRIPCION)DESC_CODSERCOMP,

DECODE(SC.DESCSERCOMP,NULL,'NO EXISTE',SC.DESCSERCOMP)DESCSERCOMP,
DECODE(SC.CANFORM,NULL,'NO EXISTE',SC.CANFORM)CANFORM,
DECODE(SC.CADAFREUSO,NULL,'NO EXISTE',SC.CADAFREUSO)CADAFREUSO,

DECODE(SC.CODFREUSO,NULL,'NO EXISTE',SC.CODFREUSO)CODFREUSO,--11. Lista(Medi-CodFreAdmon)
DECODE(FU.DESCRIPCION,NULL,'NO EXISTE',FU.DESCRIPCION) AS DESC_CODFREUSO,

DECODE(SC.CANT,null,'NO EXISTE',SC.CANT)CANT,
DECODE(SC.CANTTOTAL,NULL,'NO EXISTE',SC.CANTTOTAL)CANTTOTAL,

DECODE(SC.CODPERDURTRAT,NULL,'NO EXISTE',SC.CODPERDURTRAT)CODPERDURTRAT,--11. Lista(Medi-CodFreAdmon)
DECODE(PD.DESCRIPCION,NULL,'NO EXISTE',PD.DESCRIPCION) AS DESC_CODPERDURTRAT,

DECODE(SC.TIPOTRANS,NULL,'NO EXISTE',SC.TIPOTRANS)TIPOTRANS,--24. Lista(TipoTrans)
DECODE(TT.DESCRIPCION,NULL,'NO EXISTE',TT.DESCRIPCION)DESC_TIPOTRANS,

DECODE(SC.REQACOM,0,'NO',1,'SI',NULL,'NO EXISTE',SC.REQACOM)REQACOM,--2. Lista(Presc-Si-NO)

DECODE(SC.TIPOIDACOMALB,NULL,'NO EXISTE',SC.TIPOIDACOMALB)TIPOIDACOMALB,--25. Lista(TipoIDAcomAlb)
DECODE(TA.DESCRIPCION,NULL,'NO EXISTE',TA.DESCRIPCION)DESC_TIPOIDACOMALB,

DECODE(SC.NROIDACOMALB,NULL,'NO EXISTE',SC.NROIDACOMALB)NROIDACOMALB,

DECODE(SC.PARENTACOMALB,NULL,'NO EXISTE',SC.PARENTACOMALB)PARENTACOMALB,--26. Lista(ParentAcomAlb)
DECODE(PA.DESCRIPCION,NULL,'NO EXISTE',PA.DESCRIPCION)DESC_PARENTACOMALB,

DECODE(SC.NOMBALB,NULL,'NO EXISTE',SC.NOMBALB)NOMBALB,
DECODE(SC.CODMUNORIALB,NULL,'NO EXISTE',SC.CODMUNORIALB)CODMUNORIALB,
DECODE(SC.CODMUNDESALB,NULL,'NO EXISTE',SC.CODMUNDESALB)CODMUNDESALB,
DECODE(SC.JUSTNOPBS,NULL,'NO EXISTE',SC.JUSTNOPBS)JUSTNOPBS,
DECODE(SC.INDREC,NULL,'NO EXISTE',SC.INDREC)INDREC,

DECODE(SC.ESTJM,NULL,'NO EXISTE',SC.ESTJM)ESTJM,--14. Lista (Medi-EstJM)
DECODE(EJ.DESCRIPCION,NULL,'NO EXISTE',EJ.DESCRIPCION) AS DESC_ESTJM

FROM WEBSERV_PRES_SERV_COMP SC
LEFT JOIN WEBSERV_REF_PRE_TI_PR TP ON SC.TIPOPREST=  TP.CODIGO
LEFT JOIN WEBSERV_PRES_PRES PP ON PP.ID_PRES=SC.ID_PRES
LEFT JOIN WEBSERV_REF_PRE_SC_PR SP ON SC.CODSERCOMP=SP.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS FU ON SC.CODFREUSO=FU.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TIEMPOS PD ON SC.CODPERDURTRAT=PD.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TI_TRANSPORTE TT ON SC.TIPOTRANS=TT.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TD_AA TA ON SC.TIPOIDACOMALB=TA.CODIGO
LEFT JOIN WEBSERV_REF_PRE_PA_AA PA ON SC.PARENTACOMALB=PA.CODIGO
LEFT JOIN WEBSERV_REF_PRE_ES_JP   EJ ON SC.ESTJM=EJ.CODIGO
;