<?php
include("JuntaProfesionales/GetJuntaProfesional/getJsonAutomatico_cont_campos_oracle.php");
include("JuntaProfesionales/GetJuntaProfesional/getJsonAutomatico_subs_campos_oracle.php");
include("Prescripcion/GetPrescripcion/getJsonAutomatico_cont_campos_oracle.php");
include("Prescripcion/GetPrescripcion/getJsonAutomatico_subs_campos_oracle.php");
include("Direccionamientos/GetDireccionamiento/getJson_cont.php");
include("Direccionamientos/GetDireccionamiento/getJson_subs.php");
include("suministros/GetSumisnistro/getJson_cont.php");
include("suministros/GetSumisnistro/getJson_subs.php");
include("ReporteEntrega/GetReporteEntregaXFecha/getJson_cont.php");
include("ReporteEntrega/GetReporteEntregaXFecha/getJson_subs.php");
include("Reportes/Tutelas/GetTutelas/getJson_cont.php");
include("Reportes/Tutelas/GetTutelas/getJson_subs.php");
?>