
--------Hacer pruebas de actualizaciones en cada tabla
/*UPDATE WEBSERV_PRES_MEDI  --WEBSERV_PRES_DISP --WEBSERV_PRES_SERV_COMP --WEBSERV_PRES_PROD_NUTR --WEBSERV_PRES_PROC
SET  DIR_IDDIRECCIONAMIENTO = 11, DIR_ID = 11
WHERE  CONORDEN = 1 
AND ID_PRES in ( select id_pres from WEBSERV_PRES_PRES where NOPRESCRIPCION='20200103131016584782');
*/

--------------------------quitar los id de direccionamiento de todos los tipos de tecnologias------------------------------------------------------ 
--MEDICAMENTOS
 UPDATE WEBSERV_PRES_MEDI  
SET  DIR_IDDIRECCIONAMIENTO = '', DIR_ID = ''
where DIR_IDDIRECCIONAMIENTO is not null AND DIR_ID is not null;

--PROCEDIMIENTOS
UPDATE WEBSERV_PRES_PROC
SET  DIR_IDDIRECCIONAMIENTO = '', DIR_ID = ''
where DIR_IDDIRECCIONAMIENTO is not null AND DIR_ID is not null;


--PRODUCTOS NUTRICIONALES
UPDATE WEBSERV_PRES_PROD_NUTR
SET  DIR_IDDIRECCIONAMIENTO = '', DIR_ID = ''
where DIR_IDDIRECCIONAMIENTO is not null AND DIR_ID is not null;

--SERVICIOS COMPEMENTARIOS
UPDATE WEBSERV_PRES_SERV_COMP
SET  DIR_IDDIRECCIONAMIENTO = '', DIR_ID = ''
where DIR_IDDIRECCIONAMIENTO is not null AND DIR_ID is not null;

--DISPOSITIVOS MEDICOS
UPDATE WEBSERV_PRES_DISP
SET  DIR_IDDIRECCIONAMIENTO = '', DIR_ID = ''
where DIR_IDDIRECCIONAMIENTO is not null AND DIR_ID is not null;


-----------------------Consultar prescripciones direccionadas------------------------------------------

select pp.NOPRESCRIPCION,pp.TIPOTEC,pp.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE,PP.CODAMBATE,PAA.DESCRIPCION DESC_CODAMBATE,
       PP.CODSERTECAENTREGAR,DESC_CODSERTECAENTREGAR,c.GEOGRAPHICLOCATIONID CodMunEnt,c.Address DirPaciente,c.Regimen 
from (
--MEDICAMENTOS
select PP.NOPRESCRIPCION,'M' as TIPOTEC, PM.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE,PP.CODAMBATE,
'' CODSERTECAENTREGAR,
'' DESC_CODSERTECAENTREGAR
from WEBSERV_PRES_PRES PP
join WEBSERV_PRES_MEDI PM ON PM.ID_PRES=PP.ID_PRES
where DIR_IDDIRECCIONAMIENTO is not null AND DIR_ID is not null

union
--PROCEDIMIENTOS
select PP.NOPRESCRIPCION,'P' as TIPO_TEC, PPR.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE,PP.CODAMBATE,
PPR.CODCUPS CODSERTECAENTREGAR,--16. Lista(CUPS)
CP.DESCRIPCION DESC_CODSERTECAENTREGAR
from WEBSERV_PRES_PRES PP
join WEBSERV_PRES_PROC PPR ON PPR.ID_PRES=PP.ID_PRES
LEFT JOIN WEBSERV_REF_PRE_CUPS CP ON CP.CODIGO=PPR.CODCUPS  
where DIR_IDDIRECCIONAMIENTO is not null AND DIR_ID is not null

union
--PRODUCTOS NUTRICIONALES
select PP.NOPRESCRIPCION,'N' as TIPO_TEC, PPN.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE,PP.CODAMBATE,
PPN.DESCPRODNUTR CODSERTECAENTREGAR,--20.Lista(productos nutricion)
PN.NOMBRE_COMERCIAL ||/*' - '|| PN.DESCR_GRUPO_NIVEL_1 ||*/' - '|| PN.PRESENTACION_COMERCIAL || PN.UNIDADES AS DESC_CODSERTECAENTREGAR
from WEBSERV_PRES_PRES PP
join WEBSERV_PRES_PROD_NUTR PPN ON PPN.ID_PRES=PP.ID_PRES
LEFT JOIN WEBSERV_REF_PRE_PR_NU PN ON PPN.DESCPRODNUTR=PN.CODIGO
where DIR_IDDIRECCIONAMIENTO is not null AND DIR_ID is not null

union
--SERVICIOS COMPEMENTARIOS
select PP.NOPRESCRIPCION,'S' as TIPO_TEC, SC.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE,PP.CODAMBATE,
SC.CODSERCOMP CODSERTECAENTREGAR,--23. Listas(Serv complem PR)  --(MIPRES)17. Listas Servicios complementarios PR
SP.DESCRIPCION ||' - '|| SC.DESCSERCOMP DESC_CODSERTECAENTREGAR
from WEBSERV_PRES_PRES PP
join WEBSERV_PRES_SERV_COMP SC ON SC.ID_PRES=PP.ID_PRES
LEFT JOIN WEBSERV_REF_PRE_SC_PR SP ON SC.CODSERCOMP=SP.CODIGO
where DIR_IDDIRECCIONAMIENTO is not null AND DIR_ID is not null

union
--DISPOSITIVOS MEDICOS
select PP.NOPRESCRIPCION,'D' as TIPO_TEC, PD.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE,PP.CODAMBATE,
PD.CODDISP CODSERTECAENTREGAR,--17.Lista(Tipos disp médi)
TM.DESCRIPCION DESC_CODSERTECAENTREGAR
from WEBSERV_PRES_PRES PP
join WEBSERV_PRES_DISP PD ON PD.ID_PRES=PP.ID_PRES
LEFT JOIN WEBSERV_REF_PRE_TD_ME TM ON PD.CODDISP=TM.CODIGO
where DIR_IDDIRECCIONAMIENTO is not null AND DIR_ID is not null
) pp
LEFT JOIN client c on c.clientid=PP.NROIDPACIENTE  and c.TypeDocumentId=PP.TIPOIDPACIENTE
LEFT JOIN WEBSERV_REF_PRE_AMB_ATE paa ON paa.CODIGO=pp.CODAMBATE;