CREATE VIEW view_webserv_pres_info_direc  AS 
 --Al momento de direccionar se debe insertar un 1 en el campo "dieccionado"
select pp.NOPRESCRIPCION,pp.TIPOTEC,pp.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE,c.GEOGRAPHICLOCATIONID CodMunEnt,c.Address DirPaciente from (
--MEDICAMENTOS
select PP.NOPRESCRIPCION,'M' as TIPOTEC, PM.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE
from WEBSERV_PRES_PRES PP
join WEBSERV_PRES_MEDI PM ON PM.ID_PRES=PP.ID_PRES
where IDDIRECCIONAMIENTO is null
union
--PROCEDIMIENTOS
select PP.NOPRESCRIPCION,'P' as TIPO_TEC, PPR.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE
from WEBSERV_PRES_PRES PP
join WEBSERV_PRES_PROC PPR ON PPR.ID_PRES=PP.ID_PRES
where IDDIRECCIONAMIENTO is null
union
--PRODUCTOS NUTRICIONALES
select PP.NOPRESCRIPCION,'N' as TIPO_TEC, PN.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE
from WEBSERV_PRES_PRES PP
join WEBSERV_PRES_PROD_NUTR PN ON PN.ID_PRES=PP.ID_PRES
where IDDIRECCIONAMIENTO is null
union
--SERVICIOS COMPEMENTARIOS
select PP.NOPRESCRIPCION,'S' as TIPO_TEC, SC.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE
from WEBSERV_PRES_PRES PP
join WEBSERV_PRES_SERV_COMP SC ON SC.ID_PRES=PP.ID_PRES
where IDDIRECCIONAMIENTO is null
union
--DISPOSITIVOS MEDICOS
select PP.NOPRESCRIPCION,'D' as TIPO_TEC, PD.CONORDEN,PP.TIPOIDPACIENTE,PP.NROIDPACIENTE
from WEBSERV_PRES_PRES PP
join WEBSERV_PRES_DISP PD ON PD.ID_PRES=PP.ID_PRES
where IDDIRECCIONAMIENTO is null
) pp
left join client c on c.clientid=PP.NROIDPACIENTE  and c.TypeDocumentId=PP.TIPOIDPACIENTE