--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_EPS
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_EPS" 
   (	"CODIGO" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_EPS"  IS 'EPS';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_EPS
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF007','CAJA DE COMPENSACIÓN FAMILIAR  DE CARTAGENA - COMFAMILIAR CARTAGENA','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF009','CAJA DE COMPENSACIÓN FAMILIAR DE BOYACÁ - COMFABOY','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF015','CAJA DE COMPENSACION FAMILIAR DE CORDOBA - COMFACOR','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF023','CAJA DE COMPENSACIÓN FAMILIAR DE LA GUAJIRA - COMFAGUAJIRA','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF024','CAJA DE COMPENSACIÓN FAMILIAR DEL HUILA - COMFAMILIAR HUILA','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF027','CAJA DE COMPENSACIÓN FAMILIAR DE NARIÑO - COMFAMILIAR NARIÑO','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF033','CAJA DE COMPENSACIÓN FAMILIAR DE SUCRE - COMFASUCRE','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF050','CAJA DE COMPENSACIÓN FAMILIAR C.C.F. DEL ORIENTE COLOMBIANO - COMFAORIENTE','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF053','CAJA DE COMPENSACIÓN FAMILIAR DE CUNDINAMARCA - COMFACUNDI','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF055','CAJA DE COMPENSACION FAMILIAR  CAJACOPI ATLANTICO','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCF102','CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ - COMFACHOCO','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC07','CAJA DE COMPENSACIÓN FAMILIAR  DE CARTAGENA - COMFAMILIAR CARTAGENA -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC09','CAJA DE COMPENSACIÓN FAMILIAR  DE BOYACÁ - COMFABOY -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC15','CAJA DE COMPENSACION FAMILIAR DE CORDOBA - COMFACOR -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC20','CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ - COMFACHOCO -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC23','CAJA DE COMPENSACIÓN FAMILIAR DE LA GUAJIRA - COMFAGUAJIRA -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC24','CAJA DE COMPENSACIÓN FAMILIAR DEL HUILA - COMFAMILIAR HUILA -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC27','CAJA DE COMPENSACIÓN FAMILIAR DE NARIÑO - COMFAMILIAR NARIÑO -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC33','CAJA DE COMPENSACIÓN FAMILIAR DE SUCRE - COMFASUCRE -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC50','CAJA DE COMPENSACIÓN FAMILIAR C.C.F. DEL ORIENTE COLOMBIANO - COMFAORIENTE -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC53','CAJA DE COMPENSACIÓN FAMILIAR DE CUNDINAMARCA - COMFACUNDI -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('CCFC55','CAJA DE COMPENSACION FAMILIAR  CAJACOPI ATLANTICO -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EAS016','EMPRESAS PUBLICAS DE MEDELLIN - DEPARTAMENTO MEDICO','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EAS027','FONDO PASIVO SOCIAL DE LOS FERROCARRILES NACIONALES','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS001','ALIANSALUD E.P.S.','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS002','SALUD TOTAL S.A. ','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS003','CAFESALUD E.P.S.','0','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS005','E.P.S. SANITAS','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS008','COMPENSAR E.P.S.','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS010','EPS Y MEDICINA PREPAGADA SURAMERICANA S.A','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS012','COMFENALCO VALLE ','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS016','COOMEVA E.P.S. S.A.','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS017','FAMISANAR E.P.S. LTDA - CAFAM - COLSUBSIDIO','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS018','SERVICIO OCCIDENTAL DE SALUD - S.O.S. S.A.','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS022','A.R.S. CONVIDA','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS023','CRUZ BLANCA E.P.S.','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS025','CAJA DE PREVISION SOCIAL Y SEGURIDAD DEL CASANARE - CAPRESOCA E.P.S.','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS033','SALUDVIDA S.A. E.P.S.','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS037','NUEVA EPS S.A','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS040','SAVIA SALUD E.P.S. -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS041','NUEVA EPS S.A. -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS042','COOSALUD ENTIDAD PROMOTORA DE SALUD S.A. ','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS044 ','MEDIMAS EPS S.A.S. CONTRIBUTIVO','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPS046','FUNDACION SALUD MIA EPS','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSC22','EPS CONVIDA -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSC25','CAJA DE PREVISION SOCIAL Y SEGURIDAD DEL CASANARE - CAPRESOCA E.P.S. -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSC33 ','SALUDVIDA  S.A.  E.P.S.-CM ','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSC34','CAPITAL SALUD E.P.S. -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSI01','ASOCIACIÓN INDÍGENA DEL CESAR Y LA GUAJIRA - DUSAKAWI','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSI02','MANEXKA EPSI','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSI03','ASOCIACIÓN INDÍGENA DEL CAUCA - AIC','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSI04','ANASWAYUU EPSI','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSI05','MALLAMAS EPSI','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSI06','PIJAOS SALUD EPSI','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSIC1','ASOCIACIÓN INDÍGENA DEL CESAR Y LA GUAJIRA - DUSAKAWI -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSIC2','MANEXKA EPSI -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSIC3','ASOCIACIÓN INDÍGENA DEL CAUCA - AIC -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSIC4','ANASWAYUU EPSI -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSIC5','MALLAMAS EPSI -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSIC6','PIJAOS SALUD EPSI -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSM33','SALUDVIDA S.A. EPS -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS01','ALIANSALUD E.P.S. -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS02','SALUD TOTAL E.P.S. -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS03','CAFESALUD  E.P.S.  S.A.','0','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS05','EPS SANITAS - CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS08','COMPENSAR E.P.S. -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS10','EPS Y MEDICINA PREPAGADA SURAMERICANA S.A -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS12','COMFENALCO VALLE -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS16','COOMEVA E.P.S. S.A. -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS17','FAMISANAR E.P.S. LTDA - CAFAM - COLSUBSIDIO -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS18','SERVICIO OCCIDENTAL DE SALUD - S.O.S. S.A. -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS23','CRUZ BLANCA E.P.S. -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS33','SALUDVIDA S.A .E.P.S','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS34','CAPITAL SALUD E.P.S.','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS37','NUEVA EPS S.A. -CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS40','SAVIA SALUD E.P.S.','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS41','NUEVA EPS S.A.','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS44','MEDIMAS EPS S.A.S. - CM','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS45','MEDIMAS EPS S.A.S. SUBSIDIADO','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('EPSS46','FUNDACION SALUD MIA EPS','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESS002','EMPRESA MUTUAL PARA EL DESARROLLO INTEGRAL DE LA SALUD - EMDISALUD ESS','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESS024','COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA LTDA. - COOSALUD E.S.S.','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESS062','ASOCIACIÓN MUTUAL LA ESPERANZA - ASMET  SALUD','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESS076','ASOCIACIÓN MUTUAL BARRIOS UNIDOS DE QUIBDÓ E.S.S. - AMBUQ','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESS091','EMPRESA PROMOTORA DE SALUD ECOOPSOS EPS S.A.S.','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESS118','ASOCIACIÓN MUTUAL EMPRESA SOLIDARIA DE SALUD DE NARIÑO - EMSSANAR E.S.S.','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESS133','COOPERATIVA DE SALUD COMUNITARIA - COMPARTA','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESS207','ASOCIACIÓN MUTUAL SER EMPRESA SOLIDARIA DE SALUD E.S.S.','1','2',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESSC02','EMPRESA MUTUAL PARA EL DESARROLLO INTEGRAL DE LA SALUD - EMDISALUD E.S.S. -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESSC07','ASOCIACIÓN MUTUAL SER EMPRESA SOLIDARIA DE SALUD E.S.S. -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESSC18','ASOCIACIÓN MUTUAL EMPRESA SOLIDARIA DE SALUD DE NARIÑO - EMSSANAR E.S.S. -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESSC24','COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA - COOSALUD E.S.S. -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESSC33','COOPERATIVA DE SALUD COMUNITARIA - COMPARTA -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESSC62','ASOCIACIÓN MUTUAL LA ESPERANZA - ASMET  SALUD -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESSC76','ASOCIACIÓN MUTUAL BARRIOS UNIDOS DE QUIBDÓ E.S.S. - AMBUQ -CM','1','1',null);
Insert into OASIS4.WEBSERV_REF_PRE_EPS (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('ESSC91','EMPRESA PROMOTORA DE SALUD ECOOPSOS EPS S.A.S.','1','2',null);
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_EPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_EPS_PK" ON "OASIS4"."WEBSERV_REF_PRE_EPS" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_EPS
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_EPS" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_EPS" ADD CONSTRAINT "WEBSERV_REF_PRE_EPS_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
