--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_PRES_INDI_UNIRS
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_PRES_INDI_UNIRS" 
   (	"ID_IMUN" NUMBER, 
	"ID_MEDI" NUMBER, 
	"CONORDEN" NUMBER, 
	"CODINDICACION" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
REM INSERTING into OASIS4.WEBSERV_PRES_INDI_UNIRS
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('221','6282','1','143');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('222','6363','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('83','4991','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('81','4987','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('82','4987','1','99');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('181','6068','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('241','6443','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('1','213','1','87');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('2','509','1','117');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('3','604','1','84');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('4','625','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('5','752','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('6','866','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('7','923','1','72');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('8','964','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('9','1033','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('10','1246','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('11','1247','2','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('12','1262','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('13','1609','1','161');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('35','4180','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('161','5918','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('61','4796','1','22');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('301','7201','1','108');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('302','7240','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('303','7317','1','84');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('304','7325','1','84');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('305','7526','1','111');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('306','7560','1','111');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('201','6250','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('261','6564','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('101','5000','1','85');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('41','4657','2','104');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('42','4658','3','104');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('102','5131','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('121','5162','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('122','5162','1','99');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('123','5260','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('141','5440','1','87');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('142','5443','1','87');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('143','5470','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('281','6713','2','87');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('282','6733','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('283','6737','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('284','6762','1','28');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('285','6763','2','114');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('286','6768','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('321','7830','1','96');
--------------------------------------------------------
--  DDL for Index PRES_INDI_UNIRS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."PRES_INDI_UNIRS_PK" ON "OASIS4"."WEBSERV_PRES_INDI_UNIRS" ("ID_IMUN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_PRES_INDI_UNIRS
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_PRES_INDI_UNIRS" MODIFY ("ID_IMUN" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_PRES_INDI_UNIRS" ADD CONSTRAINT "PRES_INDI_UNIRS_PK" PRIMARY KEY ("ID_IMUN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEBSERV_PRES_INDI_UNIRS
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_PRES_INDI_UNIRS" ADD CONSTRAINT "PRES_INDI_UNIRS_ID_MEDI_FK" FOREIGN KEY ("ID_MEDI")
	  REFERENCES "OASIS4"."WEBSERV_PRES_MEDI" ("ID_MEDI") ENABLE;
