--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_WEBSERVICES
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_WEBSERVICES" 
   (	"WS_ID" NUMBER(11,0), 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"DESCRIPCION" VARCHAR2(1200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
REM INSERTING into OASIS4.WEBSERV_WEBSERVICES
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_WEBSERVICES (WS_ID,NOMBRE,DESCRIPCION) values ('1','WSPRESCRIPCIÓN',null);
Insert into OASIS4.WEBSERV_WEBSERVICES (WS_ID,NOMBRE,DESCRIPCION) values ('2','WSSUMINISTROAPI',null);
--------------------------------------------------------
--  DDL for Index PK_WEBSERV_WEBSERVICES
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."PK_WEBSERV_WEBSERVICES" ON "OASIS4"."WEBSERV_WEBSERVICES" ("WS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_WEBSERVICES
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_WEBSERVICES" MODIFY ("WS_ID" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_WEBSERVICES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_WEBSERVICES" ADD CONSTRAINT "PK_WEBSERV_WEBSERVICES" PRIMARY KEY ("WS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
