--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_PRES_DISP
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_PRES_DISP" 
   (	"ID_DISP" NUMBER, 
	"ID_PRES" NUMBER, 
	"CONORDEN" NUMBER, 
	"TIPOPREST" NUMBER, 
	"CAUSAS1" NUMBER, 
	"CODDISP" VARCHAR2(2000 BYTE), 
	"CANFORM" VARCHAR2(2000 BYTE), 
	"CADAFREUSO" VARCHAR2(2000 BYTE), 
	"CODFREUSO" VARCHAR2(2000 BYTE), 
	"CANT" VARCHAR2(2000 BYTE), 
	"CODPERDURTRAT" NUMBER, 
	"CANTTOTAL" VARCHAR2(2000 BYTE), 
	"JUSTNOPBS" VARCHAR2(2000 BYTE), 
	"INDREC" VARCHAR2(2000 BYTE), 
	"ESTJM" NUMBER, 
	"DIR_IDDIRECCIONAMIENTO" NUMBER DEFAULT NULL, 
	"DIR_ID" NUMBER, 
	"DIR_MENSAJE_ERROR" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
REM INSERTING into OASIS4.WEBSERV_PRES_DISP
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_PRES_DISP (ID_DISP,ID_PRES,CONORDEN,TIPOPREST,CAUSAS1,CODDISP,CANFORM,CADAFREUSO,CODFREUSO,CANT,CODPERDURTRAT,CANTTOTAL,JUSTNOPBS,INDREC,ESTJM,DIR_IDDIRECCIONAMIENTO,DIR_ID,DIR_MENSAJE_ERROR) values ('1','9266','1','1','1','044','1','1','8',null,null,'1','PACIENTE OPERADO DE EVISCERACION Y ENUCLEACION DEL GLOBO OCULAR DEL OJO IZQUIERDO POR FUERTE INFECCIÓN Y PERFORACIÓN DE LA CORNEA','SE ORDENA ADAPTACIÓN DE PRÓTESIS OCULAR PARA EVITAR CIERRE DE LA CAVIDAD ORBITARIA Y MEJORAR EL ASPECTO F�?SICO Y PSICOLÓGICO','1',null,null,null);
--------------------------------------------------------
--  DDL for Index WEBSERV_PRES_DISP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_PRES_DISP_PK" ON "OASIS4"."WEBSERV_PRES_DISP" ("ID_DISP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_PRES_DISP
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_PRES_DISP" MODIFY ("ID_DISP" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_PRES_DISP" ADD CONSTRAINT "WEBSERV_PRES_DISP_PK" PRIMARY KEY ("ID_DISP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEBSERV_PRES_DISP
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_PRES_DISP" ADD CONSTRAINT "PRES_DISP_ID_PRES_FK" FOREIGN KEY ("ID_PRES")
	  REFERENCES "OASIS4"."WEBSERV_PRES_PRES" ("ID_PRES") ENABLE;
