--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_UN_ME
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_UN_ME" 
   (	"ID_UNME" NUMBER, 
	"CODIGO" NUMBER, 
	"DESCRIPCION2" VARCHAR2(4000 BYTE), 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_UN_ME"  IS 'Dosis Unidad Medida';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_UN_ME
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('121','121','MBq/g','megabecquerel(ios)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('122','122','MBq/kg','megabecquerel(ios)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('123','123','MBq/l','megabecquerel(ios)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('124','124','MBq/µg','megabecquerel(ios)/microgramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('125','125','MBq/µl','megabecquerel(ios)/microlitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('126','126','MBq/mg','megabecquerel(ios)/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('127','127','MBq/ml','megabecquerel(ios)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('128','128','m','metro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('129','129','µCi','microcurio(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('130','130','µCi/g','microcurio(s)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('131','131','µCi/kg','microcurio(s)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('132','132','µCi/l','microcurio(s)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('133','133','µCi/µg','microcurio(s)/microgramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('134','134','µCi/µl','microcurio(s)/microlitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('135','135','µCi/mg','microcurio(s)/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('136','136','µCi/ml','microcurio(s)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('137','137','µg','microgramo(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('138','138','µg/m3','microgramo(s)/metro cúbico','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('139','139','µg/kg','microgramo(s)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('140','140','µg/l','microgramo(s)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('141','141','µg/µl','microgramo(s)/microlitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('142','142','µg/ml','microgramo(s)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('143','143','µg/m2','microgramo(s)/metro cuadrado','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('144','144','µkat','microkatal','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('145','145','µkat','microkatales','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('146','146','µl','microlitro(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('147','147','µl/ml','microlitro(s)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('148','148','µmol','micromol(es)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('149','149','µmol/l','micromol(es)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('150','150','µmol/ml','micromol(es)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('151','151','mCi','milicurio(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('152','152','mCi/g','milicurio(s)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('153','153','mCi/kg','milicurio(s)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('154','154','mCi/l','milicurio(s)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('155','155','mCi/µg','milicurio(s)/microgramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('156','156','mCi/µl','milicurio(s)/microlitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('157','157','mCi/mg','milicurio(s)/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('158','158','mCi/ml','milicurio(s)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('159','159','mEq','miliequivalente(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('160','160','mEq/g','miliequivalente(s)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('161','161','mEq/kg','miliequivalente(s)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('162','162','mEq/l','miliequivalente(s)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('163','163','mEq/µg','miliequivalente(s)/microgramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('164','164','mEq/µl','miliequivalente(s)/microlitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('165','165','mEq/mg','miliequivalente(s)/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('166','166','mEq/ml','miliequivalente(s)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('167','167','mg (titer)','miligramo (titer)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('168','168','mg','miligramo(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('169','169','mg/m3','miligramo(s)/metro cúbico','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('170','170','mg/g','miligramo(s)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('171','171','mg/kg','miligramo(s)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('172','172','mg/l','miligramo(s)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('173','173','mg/ml','miligramo(s)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('174','174','mg/m2','miligramo(s)/metro cuadrado','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('175','175','mkatal','milikatal','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('176','176','ml','mililitro(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('177','177','ml/cm2','mililitro(s)/centímetro cuadrado','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('178','178','mm','milimetro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('179','179','mmol','milimol(es)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('180','180','mmol/g','milimol(es)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('181','181','mmol/kg','milimol(es)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('182','182','mmol/l','milimol(es)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('183','183','mmol/ml','milimol(es)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('184','184','millon UFC','millones de unidades formadoras de colonias','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('185','185','millon UFC/g','millones de unidades formadoras de colonias/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('186','186','millon UFC/ml','millones de unidades formadoras de colonias/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('187','187','millon UI','millones de unidadades internacionales','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('188','188','millon de organismos','millon de organismos','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('189','189','millon de organismos/g','millon de organismos/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('190','190','millon de organismos/mg','millon de organismos/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('191','191','millon de organismos/ml','millon de organismos/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('192','192','millon de unidades USP','millon de unidades de la Farmacopea de los Estados Unidos','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('193','193','millon de unidades','millon de unidades','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('194','194','mOsm/kg','miliosmol(es)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('195','195','min','minuto','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('196','196','mol','mol(es)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('197','197','mol/g','mol(es)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('198','198','mol/kg','mol(es)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('199','199','mol/l','mol(es)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('200','200','mol/mg','mol(es)/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('201','201','mol/ml','mol(es)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('202','202','nCi','nanocurio(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('203','203','ng','nanogramo(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('204','204','nkat','nanokatal','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('205','205','nl','nanolitro(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('206','206','nmol','nanomol(es)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('207','207','nmol/ml','nanomol(es)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('208','208','N','newton','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('209','209','unidades NIH/cm2','NIH unidades de trombina inactivada/centímetro cuadrado','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('210','210','?','ohmio','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('211','211','OZ','onza','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('212','212','PPM','parte por millon','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('213','213','PPM','pascal','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('214','214','%','porcentaje','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('215','215','% (v/v)','porcentaje volumen/volumen','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('216','216','% (p/v)','porcentaje peso/volumen','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('217','217','% (p/p)','porcentaje peso/peso','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('218','218','pg','picogramo(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('219','219','pkat','picokatal','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('220','220','PFU','unidades formadoras de placa','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('221','221','PFU e. 1000 LD50 en ratón','unidad formadora de placa equivalente a  1000 DL50 en ratón','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('222','222','PFU/dosis','unidades formadoras de placa/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('223','223','PFU/ml','unidades formadoras de placa/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('224','224','unidad formadora de viruela','unidad(es) formadoras de viruela','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('225','225','LB','libra','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('226','226','unidades de presión/ml','unidades de presión/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('227','227','PNU/ml','unidades de nitrogeno proteico/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('228','228','QS','cantidad suficiente','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('229','229','r/min','revoluciones/minuto','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('230','230','s','segundos','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('231','231','S','siemens','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('232','232','Sv','sievert','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('233','233','cm2','centímetro cuadrado','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('234','234','m2','metro cuadrado','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('235','235','T','tesla','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('236','236','miles CFU','miles de unidades formadoras de colonia','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('237','237','miles CFU/g','miles de unidades formadoras de colonia/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('238','238','miles CFU/ml','miles de unidades formadoras de colonia/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('239','239','miles de organismos','miles de organismos','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('240','240','miles de organismos/g','miles de organismos/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('241','241','miles de organismos/ml','miles de organismos/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('242','242','TCID50/dosis','dosis infecciosa de cultivo tisular 50/ dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('243','243','titre','titre','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('244','244','t','tonelada','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('245','245','unidad de tuberculina','unidad(es) de tuberculina','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('246','246','unidad de tuberculina/ml','unidad(es) de tuberculina/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('247','247','U','unidades','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('248','248','U/g','unidades/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('249','249','U/ml','unidades/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('250','250','unidades USP','unidades de la Farmacopea de los Estados Unidos','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('251','251','V','voltio','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('252','252','W','vatio','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('253','253','Wb','weber','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('254','9000','Dosis','Dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('255','9001','TPU','TPU','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('256','9002','TSU','TSU','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('257','9003','DBU','DBU','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('258','9004','SU','SU','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('259','9005','IR','IR','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('260','9006','DPP','DPP','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('261','9007','HEP','HEP','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('262','9008','UT','UT','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('263','9009','SQ','SQ','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('264','9010','UB','UB','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('265','9011','DL50','Dosis letal 50','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('266','9012','AU','Unidades de Alergia','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('267','9013','BAU','Bioequivalente Unidades de Alergia','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('268','9014','PNU','Unidades de nitrogeno proteico','1','1',to_date('10/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('1','1','EID50','dosis infecciosa de embrión 50','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('2','2','EID50/dosis','dosis infecciosa de embrión 50/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('3','3','AU/ml','unidades de alergia/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('4','4','A','amperio','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('5','5','AgU','unidad(es) de antígeno','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('6','6','AgU/ml','unidad(es) de antígeno/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('7','7','ATU','unidades de antitrombina','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('8','8','anti-Xa IU','unidades internacionales de actividad anti-Xa','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('9','9','anti-Xa IU/ml','unidades internacionales de actividad anti-Xa/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('10','10','Bq','bequerel(ios)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('11','11','Bq/g','bequerel(ios)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('12','12','Bq/kg','bequerel(ios)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('13','13','Bq/l','bequerel(ios)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('14','14','Bq/µg','bequerel(ios)/microgramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('15','15','Bq/µl','bequerel(ios)/microlitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('16','16','Bq/mg','bequerel(ios)/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('17','17','Bq/ml','bequerel(ios)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('18','18','billon CFU','billon de unidades formadoras de colonia','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('19','19','billon CFU/g','billon de unidades formadoras de colonia/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('20','20','billon CFU/ml','billon de unidades formadoras de colonia/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('21','21','billon de organismos','billon de organismos','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('22','22','billon de organismos/g','billon de organismos/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('23','23','billon de organismos/mg','billon de organismos/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('24','24','billon de organismos/ml','billon de organismos/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('25','25','cd','candela','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('26','26','CCID50','dosis infecciosa cultivo celular 50','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('27','27','CCID50/dosis','dosis infecciosa cultivo celular 50/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('28','28','°C','temperatura en Celsius','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('29','29','CFU/g','unidades formadoras de colonias/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('30','30','CFU/ml','nidades formadoras de colonias/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('31','31','Co','culombio','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('32','32','m3','metro cúbico','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('33','33','Ci','curio(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('34','34','Ci/g','curie(s)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('35','35','Ci/kg','curie(s)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('36','36','Ci/litro','curie(s)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('37','37','Ci/µg','curie(s)/microgramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('38','38','Ci/µl','curie(s)/microlitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('39','39','Ci/mg','curie(s)/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('40','40','Ci/ml','curie(s)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('41','41','DAgU','unidad(es) de Antigeno D','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('42','42','DAgU/ml','unidad(es) de Antigeno D/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('43','43','d','dia','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('44','44','°','grado','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('45','45','DF','forma de dosificación','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('46','46','Gtt','gota(s)','1','1',to_date('15/03/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('47','47','unidades ELISA','unidad de ensayo inmunoenzimático','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('48','48','unidades ELISA/dosis','unidad de ensayo inmunoenzimático/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('49','49','unidades ELISA/ml','unidad de ensayo inmunoenzimático/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('50','50','F','faradio','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('51','51','FAI50','ensayo fluorescente dosis infecciosa 50','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('52','52','FAI50/dosis','ensayo fluorescente dosis infecciosa 50/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('53','53','GBq','gigabecquerel(ios)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('54','54','GBq/g','gigabecquerel/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('55','55','GBq/kg','gigabecquerel/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('56','56','GBq/l','gigabecquerel/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('57','57','GBq/µg','gigabecquerel/microgramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('58','58','GBq/µl','gigabecquerel/microlitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('59','59','GBq/mg','gigabecquerel/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('60','60','GBq/ml','gigabecquerel/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('61','61','g (titre)','gramo (titre)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('62','62','g','gramo(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('63','63','g/m3','gramo/metro cúbico','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('64','64','g/l','gramo/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('65','65','g/ml','gramo/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('66','66','g/m2','gramo/metro cuadrado','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('67','67','Gy','gray','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('68','68','H','henrio','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('69','69','Hz','hertz','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('70','70','h','hora','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('71','71','IOU','unidad(es) internacional(es) de opacidad','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('72','72','UI','unidad(es) internacional(es)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('73','73','UI/g','unidad(es) internacional(es)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('74','74','UI/kg','unidad(es) internacional(es)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('75','75','UI/l','unidad(es) internacional(es)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('76','76','UI/mg','unidad(es) internacional(es)/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('77','77','UI/ml','unidad(es) internacional(es)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('78','78','J','julio','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('79','79','KIU/ml','unidad calicreína inactivador/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('80','80','kat','katal','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('81','81','K','kelvin','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('82','82','kUI','unidad internacional de kilo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('83','83','unidades Kusp','unidad de la Farmacopea de los Estados Unidos de kilo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('84','84','unidades k','unidades kilo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('85','85','kBq','kilobecquerel(ios)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('86','86','kBq/g','kilobecquerel(ios)/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('87','87','kBq/kg','kilobecquerel(ios)/kilogramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('88','88','kBq/l','kilobecquerel(ios)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('89','89','kBq/µg','kilobecquerel(ios)/microgramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('90','90','kBq/µl','kilobecquerel(ios)/microlitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('91','91','kBq/mg','kilobecquerel(ios)/miligramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('92','92','kBq/ml','kilobecquerel(ios)/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('93','93','kg','kilogramo(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('94','94','kg/m3','kilogramo(s)/metro cúbico','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('95','95','kg/l','kilogramo(s)/litro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('96','96','kg/m2','kilogramo(s)/metro cuadrado','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('97','97','LacU','unidades de lactasa','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('98','98','LfU','unidades de floculación (lime flocculation unit(s))','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('99','99','LfU/ml','unidades de floculación (lime flocculation unit(s))/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('100','100','l','litro(s)','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('101','101','log10 EID50','log 10 50% dosis infecciosa de embrión','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('102','102','log10 EID51/dosis','log 10 50% dosis infecciosa de embrión/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('103','103','log10 CCID50','log10 dosis infecciosa cultivo celular 50','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('104','104','log10 CCID50/dosis','log10 dosis infecciosa de cultivo celular 50/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('105','105','log10 unidades ELISA','log10 unidad de ensayo inmunoenzimático','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('106','106','log10 unidades ELISA/dosis','log10 unidad de ensayo inmunoenzimático/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('107','107','log10 FAI50','log10 ensayo fluorescente dosis infecciosa del 50%','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('108','108','log10 FAI50/dosis','log10 ensayo fluorescente dosis infecciosa del 50%/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('109','109','log10 PFU','log10 unidad(es) formadoras de placa','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('110','110','log10 PFU/dosis','log10 unidad(es) formadoras de placa/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('111','111','log10 TCID50','log10 dosis infecciosa de cultivo tisular 50% ','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('112','112','log10 TCID50/dosis','log10 dosis infecciosa de cultivo tisular 50%/dosis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('113','113','log10/ml','log10/ml','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('114','114','LU','unidades de loomis','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('115','115','LU/g','unidades de loomis/gramo','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('116','116','LU/ml','unidades de loomis/mililitro','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('117','117','lm','lumen','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('118','118','lx','lux','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('119','119','unidades MUSP','mega; unidad de la Farmacopea de los Estados Unidos','1','1',to_date('18/11/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_UN_ME (ID_UNME,CODIGO,DESCRIPCION2,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('120','120','MBq','megabecquerel(ios)','1','1',to_date('18/11/18','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_UN_ME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_UN_ME_PK" ON "OASIS4"."WEBSERV_REF_PRE_UN_ME" ("ID_UNME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index REF_PRE_UN_ME_CODIGO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_UN_ME_CODIGO_UK1" ON "OASIS4"."WEBSERV_REF_PRE_UN_ME" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_UN_ME
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_UN_ME" MODIFY ("ID_UNME" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_UN_ME" ADD CONSTRAINT "WEBSERV_REF_PRE_UN_ME_PK" PRIMARY KEY ("ID_UNME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_UN_ME" ADD CONSTRAINT "REF_PRE_UN_ME_CODIGO_UK1" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
