--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_TD_AA
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_TD_AA" 
   (	"ID_TDAA" NUMBER, 
	"CODIGO" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_TD_AA"  IS 'Tipo de Documento de Identificación del
acompañante albergue';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_TD_AA
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('21','AS','Adulto sin Identificación',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('23','MS','Menor sin Identificación',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('1','CC',' Cédula de Ciudadanía',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('2','RC',' Registro Civil',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('3','TI',' Tarjeta de Identidad',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('4','CE',' Cédula de Extranjería',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('5','PA',' Pasaporte',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('6','NV',' Nacido Vivo',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('7','CD',' Carné Diplomático',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('8','SC',' Salvoconducto de permanencia',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('9','PR',' Pasaporte de laONU',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TD_AA (ID_TDAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('10','PE',' Permiso Especial de Permanencia',null,null,null);
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_TD_AA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_TD_AA_PK" ON "OASIS4"."WEBSERV_REF_PRE_TD_AA" ("ID_TDAA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index REF_PRE_TD_AA_CODIGO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_TD_AA_CODIGO_UK" ON "OASIS4"."WEBSERV_REF_PRE_TD_AA" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_TD_AA
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TD_AA" MODIFY ("ID_TDAA" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TD_AA" ADD CONSTRAINT "WEBSERV_REF_PRE_TD_AA_PK" PRIMARY KEY ("ID_TDAA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TD_AA" ADD CONSTRAINT "REF_PRE_TD_AA_CODIGO_UK" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
