--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_SC_PR
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_SC_PR" 
   (	"ID_SCPR" NUMBER, 
	"CODIGO" NUMBER, 
	"FECHA_CODIGO" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_SC_PR"  IS 'Servicios complementarios prescripción';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_SC_PR
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('1','1','ANTES DEL 1-OCT-2019','BLOQUEADORES SOLARES','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('2','2','ANTES DEL 1-OCT-2019','CHAMPÚ Y LOCIONES CAPILARES ','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('3','3','ANTES DEL 1-OCT-2019','MEDIAS DE COMPRESIÓN GRADUADA Y ANTIEMBÓLICAS','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('4','4','ANTES DEL 1-OCT-2019','PAÑALES','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('5','5','ANTES DEL 1-OCT-2019','ZAPATOS Y PLANTILLAS ORTOPÉDICAS','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('6','6','ANTES DEL 1-OCT-2019','TRATAMIENTOS DE ORTODONCIA','0','1',to_date('25/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('7','7','ANTES DEL 1-OCT-2019','TRATAMIENTOS DE PERIODONCIA','0','1',to_date('25/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('8','8','ANTES DEL 1-OCT-2019','IMPLANTOLOGÍA DENTAL','0','1',to_date('25/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('9','9','ANTES DEL 1-OCT-2019','LENTES DE CONTACTO','1','1',to_date('25/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('10','10','ANTES DEL 1-OCT-2019','TRANSPORTE AMBULATORIO DIFERENTE A AMBULANCIA NO PBS-UPC','1','1',to_date('22/03/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('11','11','ANTES DEL 1-OCT-2019','TRANSPORTE AMBULANCIA NO CUBIERTO POR EL PBS-UPC','0','1',to_date('09/05/19','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('12','12','ANTES DEL 1-OCT-2019','HOSPEDAJE, ALIMENTACIÓN Y VIÁTICOS CONTEMPLADOS EN LEYES ESPECIALES DIFERENTES A LOS OTORGADOS A LAS COMUNIDADES INDÍGENAS','0','1',to_date('21/05/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('13','108','DESPUES DEL 1-OCT-2019','BLOQUEADORES SOLARES','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('14','109','DESPUES DEL 1-OCT-2019','CHAMPÚ Y LOCIONES CAPILARES ','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('15','132','DESPUES DEL 1-OCT-2019','MEDIAS DE COMPRESIÓN GRADUADA Y ANTIEMBÓLICAS','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('16','139','DESPUES DEL 1-OCT-2019','PAÑALES','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('17','156','DESPUES DEL 1-OCT-2019','ZAPATOS Y PLANTILLAS ORTOPÉDICAS','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('18','153','DESPUES DEL 1-OCT-2019','TRATAMIENTOS DE ORTODONCIA','0','1',to_date('25/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('19','154','DESPUES DEL 1-OCT-2019','TRATAMIENTOS DE PERIODONCIA','0','1',to_date('25/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('20','123','DESPUES DEL 1-OCT-2019','IMPLANTOLOGÍA DENTAL','0','1',to_date('25/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('21','128','DESPUES DEL 1-OCT-2019','LENTES DE CONTACTO','1','1',to_date('25/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('22','150','DESPUES DEL 1-OCT-2019','TRANSPORTE AMBULATORIO DIFERENTE A AMBULANCIA NO PBS-UPC','1','1',to_date('22/03/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('23','149','DESPUES DEL 1-OCT-2019','TRANSPORTE AMBULANCIA NO CUBIERTO POR EL PBS-UPC','0','1',to_date('09/05/19','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_SC_PR (ID_SCPR,CODIGO,FECHA_CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('24','122','DESPUES DEL 1-OCT-2019','HOSPEDAJE, ALIMENTACIÓN Y VIÁTICOS CONTEMPLADOS EN LEYES ESPECIALES DIFERENTES A LOS OTORGADOS A LAS COMUNIDADES INDÍGENAS','0','1',to_date('21/05/18','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_SC_PR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_SC_PR_PK" ON "OASIS4"."WEBSERV_REF_PRE_SC_PR" ("ID_SCPR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index REF_PRE_SC_PR_CODIGO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_SC_PR_CODIGO_UK" ON "OASIS4"."WEBSERV_REF_PRE_SC_PR" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_SC_PR
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_SC_PR" MODIFY ("ID_SCPR" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_SC_PR" ADD CONSTRAINT "WEBSERV_REF_PRE_SC_PR_PK" PRIMARY KEY ("ID_SCPR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_SC_PR" ADD CONSTRAINT "REF_PRE_SC_PR_CODIGO_UK" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
