--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_VI_AD
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_VI_AD" 
   (	"ID_VIAD" NUMBER, 
	"CODIGO" NUMBER, 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_VI_AD"  IS 'Vía de Administración ';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_VI_AD
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('1','1','AURICULAR (OTICA)','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('2','2','BUCAL','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('3','3','CUTANEA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('4','4','DENTAL','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('5','5','ENDOCERVICAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('6','6','ENDOSINUSIAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('7','7','ENDOTRAQUEAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('8','8','EPIDURAL','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('9','9','EXTRA-AMNIOTICO','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('10','10','VIA A TRAVES DE HEMODIALISIS','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('11','11','INTRA CORPUS CAVERNOSO','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('12','12','INTRAAMNIOTICA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('13','13','INTRAARTERIAL','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('14','14','INTRAARTICULAR','1','1',to_date('16/02/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('15','15','INTRAUTERINA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('16','16','INTRACARDIACA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('17','17','INTRACAVERNOSA','1','1',to_date('05/04/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('18','18','INTRACEREBRAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('19','19','INTRACERVICAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('20','20','INTRACISTERNAL (CEREBELOMEDULAR)','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('21','21','INTRACORNEAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('22','22','INTRACORONARIA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('23','23','INTRADERMICA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('24','24','INTRADISCAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('25','25','INTRAHEPATICA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('26','26','USO INTRALESIONAL','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('27','27','USO INTRALINFATICO','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('28','28','INTRAMEDULAR','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('29','29','INTRAMENINGEA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('30','30','INTRAMUSCULAR','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('31','31','INTRAOCULAR','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('32','32','INTRAPERICARDIAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('33','33','INTRAPERITONEAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('34','34','INTRAPLEURAL','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('35','35','INTRASINOVIAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('36','36','INTRATECAL','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('37','37','INTRATORAXICA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('38','38','INTRATRAQUEAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('39','39','INTRATUMORAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('40','40','BOLO INTRAVENOSO','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('41','41','GOTEO INTRAVENOSO','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('42','42','INTRAVENOSA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('43','43','INTRAVESICAL','1','1',to_date('05/04/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('44','44','IONTOFORESIS','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('45','45','NASAL','1','1',to_date('16/02/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('46','46','TECNICA DE VENDAJE OCLUSIVO','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('47','47','OFTALMICA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('48','48','ORAL','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('49','49','OROFARINGEA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('50','50','OTRA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('51','51','PARENTERAL*','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('52','52','PERIARTICULAR','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('53','53','PERINEURAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('54','54','RECTAL','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('55','55','INHALATORIA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('56','56','RETROBULBAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('57','57','SUBCONJUNTIVAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('58','58','SUBCUTANEA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('59','60','SUBLINGUAL','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('60','61','TOPICA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('61','62','TRANSDERMICA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('62','63','TRANSMAMARIA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('63','64','TRANSPLACENTARIA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('64','66','URETRAL','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('65','67','VAGINAL','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('66','68','CONJUNTIVAL','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('67','69','ELECTRO-OSMOSIS','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('68','70','ENTERAL','1','1',to_date('24/10/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('69','71','GASTROENTERAL','1','1',to_date('24/10/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('70','72','INTRAGINGIVAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('71','75','IN VITRO','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('72','76','INFILTRACION','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('73','77','INTERSTICIAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('74','78','INTRABDOMINAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('75','79','INTRABILIAR','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('76','80','INTRABRONQUIAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('77','81','INTRABURSAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('78','82','INTRACARTILAGINOSO','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('79','83','INTRACAUDAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('80','84','INTRACAVITARIA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('81','85','INTRACORONARIO, DENTAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('82','86','INTRADUCTAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('83','87','INTRADUODENAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('84','88','INTRADURAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('85','89','INTRAEPIDERMAL','1','1',to_date('10/07/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('86','90','INTRAESOFAGICA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('87','91','INTRAGASTRICA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('88','92','INTRAILEAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('89','93','INTRAOVARICA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('90','94','INTRAPROSTATICA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('91','95','INTRAPULMONAR','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('92','96','INTRASINUSAL (SENOSPARANASALES)','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('93','97','INTRAESTERNAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('94','98','INTRATENDINOSA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('95','99','INTRATESTICULAR','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('96','100','INTRATUBULAR','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('97','101','INTRATIMPANICA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('98','102','INTRAVASCULAR','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('99','103','INTRAVENTRICULAR','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('100','104','INTRAVITREA','1','1',to_date('25/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('101','105','IRRIGACION','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('102','106','LARINGEO','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('103','107','LARINGOFARINGEAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('104','108','SONDA NASOGASTRICA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('105','110','USO OROMUCOSA','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('106','111','PERCUTANEA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('107','112','PERIDURAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('108','113','PERIODONTAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('109','114','TEJIDO BLANDO','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('110','115','SUBARACNOIDEA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('111','116','SUBMUCOSA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('112','117','TRANSMUCOSA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('113','118','TRANSTRAQUEAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('114','119','TRANSTIMPANICA','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('115','120','URETERAL','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('116','500','INTRADETRUSOR','0','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('117','501','USO EPILESIONAL','1','1',to_date('27/03/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('118','502','INHALATORIA NASAL','1','2',to_date('06/09/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_VI_AD (ID_VIAD,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('119','503','INHALATORIA BUCAL','1','2',to_date('06/09/18','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_VI_AD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_VI_AD_PK" ON "OASIS4"."WEBSERV_REF_PRE_VI_AD" ("ID_VIAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index REF_PRE_VI_AD_CODIGO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_VI_AD_CODIGO_UK1" ON "OASIS4"."WEBSERV_REF_PRE_VI_AD" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_VI_AD
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_VI_AD" MODIFY ("ID_VIAD" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_VI_AD" ADD CONSTRAINT "WEBSERV_REF_PRE_VI_AD_PK" PRIMARY KEY ("ID_VIAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_VI_AD" ADD CONSTRAINT "REF_PRE_VI_AD_CODIGO_UK1" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
