--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_TI_TRANSPORTE
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_TI_TRANSPORTE" 
   (	"ID_TITRANSPORTE" NUMBER, 
	"CODIGO" NUMBER, 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_TI_TRANSPORTE"  IS 'Tipo de transporte';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_TI_TRANSPORTE
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_TI_TRANSPORTE (ID_TITRANSPORTE,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('1','1','Terrestre',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TI_TRANSPORTE (ID_TITRANSPORTE,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('2','2','Fluvial',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TI_TRANSPORTE (ID_TITRANSPORTE,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('3','3','Aéreo',null,null,null);
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_TI_TRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_TI_TRA_PK" ON "OASIS4"."WEBSERV_REF_PRE_TI_TRANSPORTE" ("ID_TITRANSPORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index REF_PRE_TI_TRA_CODIGO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_TI_TRA_CODIGO_UK" ON "OASIS4"."WEBSERV_REF_PRE_TI_TRANSPORTE" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_TI_TRANSPORTE
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TI_TRANSPORTE" MODIFY ("ID_TITRANSPORTE" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TI_TRANSPORTE" ADD CONSTRAINT "WEBSERV_REF_PRE_TI_TRA_PK" PRIMARY KEY ("ID_TITRANSPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TI_TRANSPORTE" ADD CONSTRAINT "REF_PRE_TI_TRA_CODIGO_UK" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
