--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_PA_AA
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_PA_AA" 
   (	"ID_PAAA" NUMBER, 
	"CODIGO" NUMBER, 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_PA_AA"  IS 'Parentesco del acompañante albergue';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_PA_AA
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_PA_AA (ID_PAAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('41','1','Cónyuge o compañero(a) permanente',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_PA_AA (ID_PAAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('42','2','Hijo (a)',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_PA_AA (ID_PAAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('43','3','Padre o Madre',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_PA_AA (ID_PAAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('44','4','Segundo grado de consanguinidad',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_PA_AA (ID_PAAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('45','5','Tercer grado de consanguinidad',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_PA_AA (ID_PAAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('46','6','Menor de 12 años sin consanguinidad',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_PA_AA (ID_PAAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('47','7','Padre o Madre del cónyuge',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_PA_AA (ID_PAAA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('48','8','Otros no parientes',null,null,null);
--------------------------------------------------------
--  DDL for Index REF_PRE_PA_AA_CODIGO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_PA_AA_CODIGO_UK" ON "OASIS4"."WEBSERV_REF_PRE_PA_AA" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_PA_AA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_PA_AA_PK" ON "OASIS4"."WEBSERV_REF_PRE_PA_AA" ("ID_PAAA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_PA_AA
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_PA_AA" MODIFY ("ID_PAAA" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_PA_AA" ADD CONSTRAINT "WEBSERV_REF_PRE_PA_AA_PK" PRIMARY KEY ("ID_PAAA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_PA_AA" ADD CONSTRAINT "REF_PRE_PA_AA_CODIGO_UK" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
