--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_TI_TR
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_TI_TR" 
   (	"ID_TITR" NUMBER, 
	"CODIGO" NUMBER, 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_TI_TR"  IS 'Tipo de Transcripción';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_TI_TR
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_TI_TR (ID_TITR,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('1','1','Contingencia - Dificultades técnicas',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TI_TR (ID_TITR,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('2','2','Contingencia - No hay servicio eléctrico',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TI_TR (ID_TITR,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('3','3','Contingencia - No hay conectividad',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TI_TR (ID_TITR,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('4','4','Contingencia - Inconsistencia en afiliación o identificación',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TI_TR (ID_TITR,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('5','5','Urgencia Médica',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_TI_TR (ID_TITR,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('6','6','Donante no efectivo',null,null,null);
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_TI_TR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_TI_TR_PK" ON "OASIS4"."WEBSERV_REF_PRE_TI_TR" ("ID_TITR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index REF_PRE_TI_TR_CODIGO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_TI_TR_CODIGO_UK1" ON "OASIS4"."WEBSERV_REF_PRE_TI_TR" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_TI_TR
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TI_TR" MODIFY ("ID_TITR" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TI_TR" ADD CONSTRAINT "WEBSERV_REF_PRE_TI_TR_PK" PRIMARY KEY ("ID_TITR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TI_TR" ADD CONSTRAINT "REF_PRE_TI_TR_CODIGO_UK1" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
