--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_TIPOSERVICIOS
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_TIPOSERVICIOS" 
   (	"TISE_ID" NUMBER(11,0), 
	"WS_ID" NUMBER(11,0), 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"DESCRIPCION" VARCHAR2(1200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
REM INSERTING into OASIS4.WEBSERV_TIPOSERVICIOS
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_TIPOSERVICIOS (TISE_ID,WS_ID,NOMBRE,DESCRIPCION) values ('1','1','Prescripcion',null);
Insert into OASIS4.WEBSERV_TIPOSERVICIOS (TISE_ID,WS_ID,NOMBRE,DESCRIPCION) values ('2','2','ReporteEntrega',null);
Insert into OASIS4.WEBSERV_TIPOSERVICIOS (TISE_ID,WS_ID,NOMBRE,DESCRIPCION) values ('3','1','JuntaProfesional',null);
--------------------------------------------------------
--  DDL for Index PK_WEBSERV_TIPOSERVICIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."PK_WEBSERV_TIPOSERVICIOS" ON "OASIS4"."WEBSERV_TIPOSERVICIOS" ("TISE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_TIPOSERVICIOS
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_TIPOSERVICIOS" MODIFY ("TISE_ID" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_TIPOSERVICIOS" MODIFY ("WS_ID" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_TIPOSERVICIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_TIPOSERVICIOS" ADD CONSTRAINT "PK_WEBSERV_TIPOSERVICIOS" PRIMARY KEY ("TISE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEBSERV_TIPOSERVICIOS
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_TIPOSERVICIOS" ADD CONSTRAINT "FK_WEBSERV_TIPOSERVICIOS1" FOREIGN KEY ("WS_ID")
	  REFERENCES "OASIS4"."WEBSERV_WEBSERVICES" ("WS_ID") ENABLE;
