--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_DIAG
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_DIAG" 
   (	"ID_DIAG" NUMBER, 
	"CODIGO" NUMBER, 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_DIAG"  IS 'Diagnósticos';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_DIAG
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_DIAG (ID_DIAG,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('1','0','Diagnóstico No Confirmado',null,null,null);
Insert into OASIS4.WEBSERV_REF_PRE_DIAG (ID_DIAG,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('2','1','Diagnóstico Confirmado',null,null,null);
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_DIAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_DIAG_PK" ON "OASIS4"."WEBSERV_REF_PRE_DIAG" ("ID_DIAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index REF_PRE_DIAG_CODIGO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_DIAG_CODIGO_UK1" ON "OASIS4"."WEBSERV_REF_PRE_DIAG" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_DIAG
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_DIAG" MODIFY ("ID_DIAG" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_DIAG" ADD CONSTRAINT "WEBSERV_REF_PRE_DIAG_PK" PRIMARY KEY ("ID_DIAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_DIAG" ADD CONSTRAINT "REF_PRE_DIAG_CODIGO_UK1" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
