--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_FO_FA
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_FO_FA" 
   (	"ID_FOFA" NUMBER, 
	"CODIGO" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_FO_FA"  IS 'Forma Farmacéutica';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_FO_FA
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('1','C28944','CREMA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('2','C29167','LOCION','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('3','C29269','ENJUAGUE','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('4','C42887','AEROSOL','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('5','C42909','GRA?NULOS EFERVESCENTES','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('6','C42912','ELIXIR','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('7','C42932','CINTA ADHESIVA / PELICULA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('8','C42933','GAS','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('9','C42938','GRA?NULOS CONVENCIONALES','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('10','C42941','GOMA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('11','C42942','IMPLANTE','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('12','C42948','GELES y JALEAS','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('13','C42953','LIQUIDO (Diferentes a soluciones)','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('14','C42966','UNGUENTO','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('15','C42967','PASTA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('16','C42968','SISTEMAS TRASNDERMICOS','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('17','C42969','PELLETS','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('18','C42983','JABONES Y CHAMPU','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('19','C42989','ESPRAY','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('20','C42993','SUPOSITORIO / OVULO','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('21','C42994','SUSPENSION','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('22','C42996','JARABE','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('23','C43000','TINTURA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('24','C47913','EMPLASTO','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('25','C47914','TIRA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('26','C47915','SISTEMAS INTRAUTERINOS','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('27','C64898','ESPUMA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('28','C69031','SISTEMAS OCULARES','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('29','C91199','SISTEMAS DE ANILLOS VAGINALES','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('30','COLFF001','TABLETAS DE LIBERACION NO MODIFICADA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('31','COLFF002','POLVOS PARA NO RECONSTITUIR','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('32','COLFF003','POLVOS PARA RECONSTITUIR','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('33','COLFF004','OTRAS SOLUCIONES','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('34','COLFF005','OTRAS EMULSIONES','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('35','COLFF006','CAPSULAS DE LIBERACION NO MODIFICADA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('36','COLFF007','CAPSULAS DE LIBERACION MODIFICADA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('37','COLFF008','TABLETAS DE LIBERACION MODIFICADA','1','1',to_date('10/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('38','COLFF009','GRANULOS DE LIBERACION NO MODIFICADA','1','1',to_date('27/03/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FO_FA (ID_FOFA,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('39','COLFF010','GRANULOS DE LIBERACION MODIFICADA','1','1',to_date('27/03/18','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_FO_FA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_FO_FA_PK" ON "OASIS4"."WEBSERV_REF_PRE_FO_FA" ("ID_FOFA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index REF_PRE_FO_FA_CODIGO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_FO_FA_CODIGO_UK1" ON "OASIS4"."WEBSERV_REF_PRE_FO_FA" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_FO_FA
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_FO_FA" MODIFY ("ID_FOFA" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_FO_FA" ADD CONSTRAINT "WEBSERV_REF_PRE_FO_FA_PK" PRIMARY KEY ("ID_FOFA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_FO_FA" ADD CONSTRAINT "REF_PRE_FO_FA_CODIGO_UK1" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
