--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_LOG_ERRORES
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_LOG_ERRORES" 
   (	"SERV_ID" NUMBER(11,0), 
	"TIRE_ID" NUMBER(11,0), 
	"PERIODO" DATE, 
	"NOMBRE" VARCHAR2(1200 BYTE), 
	"DESCRIPCION" VARCHAR2(1200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
REM INSERTING into OASIS4.WEBSERV_LOG_ERRORES
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_LOG_ERRORES (SERV_ID,TIRE_ID,PERIODO,NOMBRE,DESCRIPCION) values ('3','1',to_date('13/02/20','DD/MM/RR'),'WSPRESCRIPCION: Error al consumir el WebService','No se cargó Prescripcion contributivo 2020-02-13');
Insert into OASIS4.WEBSERV_LOG_ERRORES (SERV_ID,TIRE_ID,PERIODO,NOMBRE,DESCRIPCION) values ('9','1',to_date('28/02/20','DD/MM/RR'),'WSPRESCRIPCION: Error al consumir el WebService','No se cargó JuntaProfesionalXFecha Contributivo 2020-02-28');
Insert into OASIS4.WEBSERV_LOG_ERRORES (SERV_ID,TIRE_ID,PERIODO,NOMBRE,DESCRIPCION) values ('3','1',to_date('29/02/20','DD/MM/RR'),'WSPRESCRIPCION: Error al consumir el WebService','No se cargó Prescripcion contributivo 2020-02-29');
Insert into OASIS4.WEBSERV_LOG_ERRORES (SERV_ID,TIRE_ID,PERIODO,NOMBRE,DESCRIPCION) values ('3','2',to_date('28/02/20','DD/MM/RR'),'WSPRESCRIPCION: Error al consumir el WebService','No se cargó Prescripcion subsidiado 2020-02-28');
Insert into OASIS4.WEBSERV_LOG_ERRORES (SERV_ID,TIRE_ID,PERIODO,NOMBRE,DESCRIPCION) values ('3','1',to_date('28/02/20','DD/MM/RR'),'WSPRESCRIPCION: Error al consumir el WebService','No se cargó Prescripcion contributivo 2020-02-28');
Insert into OASIS4.WEBSERV_LOG_ERRORES (SERV_ID,TIRE_ID,PERIODO,NOMBRE,DESCRIPCION) values ('3','2',to_date('29/02/20','DD/MM/RR'),'WSPRESCRIPCION: Error al consumir el WebService','No se cargó Prescripcion subsidiado 2020-02-29');
--------------------------------------------------------
--  DDL for Index PK_WEBSERV_LOG_ERRORES
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."PK_WEBSERV_LOG_ERRORES" ON "OASIS4"."WEBSERV_LOG_ERRORES" ("SERV_ID", "TIRE_ID", "PERIODO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_LOG_ERRORES
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_LOG_ERRORES" MODIFY ("SERV_ID" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_LOG_ERRORES" MODIFY ("TIRE_ID" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_LOG_ERRORES" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_LOG_ERRORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_LOG_ERRORES" ADD CONSTRAINT "PK_WEBSERV_LOG_ERRORES" PRIMARY KEY ("SERV_ID", "TIRE_ID", "PERIODO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEBSERV_LOG_ERRORES
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_LOG_ERRORES" ADD CONSTRAINT "FK_WEBSERV_LOG_ERRORES1" FOREIGN KEY ("SERV_ID")
	  REFERENCES "OASIS4"."WEBSERV_SERVICIOS" ("SERV_ID") ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_LOG_ERRORES" ADD CONSTRAINT "FK_WEBSERV_LOG_ERRORES2" FOREIGN KEY ("TIRE_ID")
	  REFERENCES "OASIS4"."WEBSERV_TIPOREPORTES" ("TIRE_ID") ENABLE;
