--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_PRES_LIST_PROV
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_PRES_LIST_PROV" 
   (	"NOIDPROV" NUMBER(11,0), 
	"NOMBRE" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
REM INSERTING into OASIS4.WEBSERV_PRES_LIST_PROV
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('901260762','DIVAED CASA DE PASO');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900254478','CASA PASO CASA MILAGRO');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('901159139','TUMEDIC');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('72125229','RODOLFO JALLER RAAD');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('77028533','WAKIS MAYORCA CASTILLA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800033723','SERVICIOS MEDICOS OLIMPUS IPS SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800117564','CLINICA DE LA MUJER S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800129856','IPS CLINICA DE LA COSTA LTDA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800130625','HOSPITAL SAN CRISTÓBAL EMPRESA SOCIAL DEL ESTADO');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800161687','UNIDAD DE GASTROENTEROLOGIA Y ENDOSCOPIA DIGESTIVA S.A.-UGASEND S.A');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800183943','CLINICA SANTA MARIA SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800191916','CLINICA SAN FRANCISCO S.A');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800194798','ORGANIZACION CLINICA BONNADONA PREVENIR S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800201726','FUNDACION POLICLINICA CIENAGA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800204919','CLINICA RESPIRATORIA Y DE ALERGIAS ');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('800231235','HOSPITAL UNIVERSITARIO SAN JORGE');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('801000713','ONCOLOGOS DEL OCCIDENTE SA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('802000955','INSTITUTO DE LA VISION DEL NORTE & CIA. LTDA.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('802004504','YEPES RESTREPO & CIA S EN C SIMPLE');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('802009783','CLINICA SAN RAFAEL LTDA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('802013835','CLINICAS ATENAS LTDA IPS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('802014564','CENTRO MEDICO CLINICA DE ALERGIA E INMUNOLOGIA SA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('802018443','INSTITUTO ONCO-HEMATOLOGICA BETANIA LTDA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('802024817','IPS MEDICAMENTOS Y EQUIPOS COLOMBIA SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('804007178','COSANMED LTDA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('806011261','ESTRIOS SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('816001182','AUDIFARMA S.A.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('817007493','FUNDACION HUELLAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('819000364','CLINICA DE LA MUJER S.A.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('823002227','INSTITUTO DE CANCEROLOGIA DE SUCRE S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('823002342','IPS CLINICA DE VARICES S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('823002800','OFTALMOLOGOS ASOCIADOS DE LA COSTA S.A.S');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('824000687','SOCIEDAD DE ONCOLOGIA Y HEMATOLOGIA DEL CESAR LTDA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('824001041','CLINICA MEDICOS S.A.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('824002277','CLINICA BUENOS AIRES S.A:S');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('824004396','MEDIVALLE SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('824004867','CLINICA OFTALMOLOGICA DE VALLEDUPAR LTDA.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('824005609','ASISTENCIA MEDICA INMEDIATA AMEDI S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('824005694','CENTRO REGIONAL DE ONCOLOGIA SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('830504734','VISION TOTAL S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('830514327','FUNDAVISION');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('860005114','LINDE COLOMBIA S.A. ');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('860015536','HOSPITAL UNIVERSITARIO SAN IGNACIO');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('890102768','ORGANIZACION CLINICA GENERAL DEL NORTE');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('890112801','FUNDACIÓN HOSPITAL UNIVERSIDAD DEL NORTE');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('890113431','CEDIUL S.A.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('890116783','UNIDAD LASER DEL ATJANTICO LTDA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('890300513','CLINICA DE OCCIDENTE');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('890303461','HOSPITAL UNIVERSITARIO DEL VAL');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('890303841','HOSPITAL DE SAN JUAN DE DIOS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('890304155','E.S.E. HOSPITAL DEPARTAMENTAL PSIQUIATRICO UNIVERSITARIO DEL VALLE');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('890324177','FUNDACION VALLE DEL LILI');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('890901826','HOSPITAL PABLO TOBON URIBE');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('892300979','CLINICA DEL CESAR S.A.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900008328','CLINICA LAURA DANIELA LTDA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900009141','DISTRIBUIDORA DE MEDICAMENTOS LIMITADA DISTRIMED LTDA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900016598','INSTITUTO CARDIOVASCULAR DEL CESAR S.A');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900036695','INTENSIVISTAS MRC IPS S.A ');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900037169','IPS CENTRO OPTICO RIOMAR');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900042103','EMPRESA SOCIAL DEL ESTADO HOSPITAL UNIVERSITARIO DEL CARIBE');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900074359','UCIMED S.A');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900112364','SOCIEDAD CARDIOVASCULAR DEL CARIBE COLOMBIANO S.A.S');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900141276','INVERSIONES SMP S.A.S');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900155383','SUMINISTROS INTEGRALES MAURO SERGIO SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900217343','CLINICA OFTALMOLOGICA DE SUCRE S.A.S');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900247710','CLINICA OFTALMOLOGICA DE CARTAGO LIMITADA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900261353','FUNDACION HOSPITAL SAN VICENTE DE PAUL RIONEGRO');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900269029','FUNDACION CENTRO COLOMBIANO DE EPILEPSIA Y ENFERMEDADES NEUROLOGICAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900277187','ASISTENCIA MEDICA IPS S A S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900337462','SUMI-INTEGRAL L.S EU.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900346567','SUMINISTROS INTEGRALES DE EQUIPOS BIOMEDICOS MEDICAMENTOS E INSUMOS HOSPITALARIOS SUMINTEGRALES S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900373755','SOLUCIONES INTEGRALES Z.P.F. S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900377997','UNIDAD MEDICA MOVIL LA CANDELARIA LTDA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900437964','CENTRO RADIOLOGICA ELISA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900441355','OSTEOBIOMED S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900472731','SALUD INTEGRAL VITAL VIDA SAS AGENCIA CARTAGO VALLE');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900496673','CODIGO AZUL SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900517932','MEDIVALLE SF SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900520293','FUNDACION UNIONVIDA QUIBDO');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900602320','CLINICA LA MISERICORDIA');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900613550','CLINICA SAN FRANCISCO DE ASIS SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900665934','DOMEDICAL IPS S.A.S');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900699317','MEDICAL HEALTH CARE IPS S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900743259','OFTALMOLOGIA DE ALTA TECNOLOGIA S.A.S');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900744042','MEDICPLUS SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900843971','MEDICAVITAL S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900862597','CIES NEUROREHABILITACION INTEGRAL S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900870339','UNIVERSO DE SOLUCIONES SAS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900873848','FUNDACIÓN FUSA PYP');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('900998064','UNIMEDICAL PACIFIC S.A.S.');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('901121329','DROGUERIA FARMA-ENTREGA DEL VALLE SF S.AS');
Insert into OASIS4.WEBSERV_PRES_LIST_PROV (NOIDPROV,NOMBRE) values ('901139193','MIRED BARRANQUILLA IPS S.A.S.');
