--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_FP_NU
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_FP_NU" 
   (	"ID_FPNU" NUMBER, 
	"CODIGO" NUMBER, 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_FP_NU"  IS 'Formas Productos Nutricionales';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_FP_NU
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('1','1','Bolsa','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('2','2','Bolsa ultrapack','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('3','3','Botella','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('4','4','EasyBag','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('5','5','Lata','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('6','6','LOC','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('7','7','LPC','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('8','8','LPM','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('9','9','Sobre','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('10','10','Tetraprisma','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('11','11','Ultrapack','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_FP_NU (ID_FPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('12','12','Frasco','1','2',to_date('01/10/18','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_FP_NU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_FP_NU_PK" ON "OASIS4"."WEBSERV_REF_PRE_FP_NU" ("ID_FPNU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index REF_PRE_FP_NU_CODIGO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_FP_NU_CODIGO_UK1" ON "OASIS4"."WEBSERV_REF_PRE_FP_NU" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_FP_NU
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_FP_NU" MODIFY ("ID_FPNU" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_FP_NU" ADD CONSTRAINT "WEBSERV_REF_PRE_FP_NU_PK" PRIMARY KEY ("ID_FPNU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_FP_NU" ADD CONSTRAINT "REF_PRE_FP_NU_CODIGO_UK1" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
