--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_TIPOREPORTES
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_TIPOREPORTES" 
   (	"TIRE_ID" NUMBER(11,0), 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"DESCRIPCION" VARCHAR2(1200 BYTE), 
	"TOKEN" VARCHAR2(250 BYTE), 
	"NIT" VARCHAR2(250 BYTE), 
	"TOKEN_TEMPORAL" VARCHAR2(250 BYTE), 
	"FECHA_TOKEN_TEMPORAL" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
REM INSERTING into OASIS4.WEBSERV_TIPOREPORTES
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_TIPOREPORTES (TIRE_ID,NOMBRE,DESCRIPCION,TOKEN,NIT,TOKEN_TEMPORAL,FECHA_TOKEN_TEMPORAL) values ('1','Contributivo','usuarios afiliados por el régimen contributivo','3858A1E4-E9BB-40D1-90E7-C127480363F2','818000140','CbPEDK79fJKdb0OyKA1Tej14krkUQdPfNScv_3Rt-90=',to_timestamp('17/02/20 04:56:09,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'));
Insert into OASIS4.WEBSERV_TIPOREPORTES (TIRE_ID,NOMBRE,DESCRIPCION,TOKEN,NIT,TOKEN_TEMPORAL,FECHA_TOKEN_TEMPORAL) values ('2','Subsidiado','usuarios afiliados por el régimen subsidiado ','208F5DB1-95D0-446E-AAD7-2674C6360A46','818000140','U9ReshqfOKJHH_Syry2ckRk4dwbKwl3qWv418D8xPzQ=',to_timestamp('02/03/20 09:12:52,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'));
--------------------------------------------------------
--  DDL for Index PK_WEBSERV_TIPOREPORTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."PK_WEBSERV_TIPOREPORTES" ON "OASIS4"."WEBSERV_TIPOREPORTES" ("TIRE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_TIPOREPORTES
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_TIPOREPORTES" MODIFY ("TIRE_ID" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_TIPOREPORTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_TIPOREPORTES" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_TIPOREPORTES" MODIFY ("NIT" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_TIPOREPORTES" ADD CONSTRAINT "PK_WEBSERV_TIPOREPORTES" PRIMARY KEY ("TIRE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
