--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_JP_TI_TE
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_JP_TI_TE" 
   (	"CODIGO" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_JP_TI_TE"  IS 'Tipo de Tecnología';
REM INSERTING into OASIS4.WEBSERV_REF_JP_TI_TE
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_JP_TI_TE (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('M','Medicamentos incluidos en la lista UNIRS',null,null,null);
Insert into OASIS4.WEBSERV_REF_JP_TI_TE (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('N','Productos nutricionales de tipo Ambulatorio',null,null,null);
Insert into OASIS4.WEBSERV_REF_JP_TI_TE (CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('S','Servicios Complementarios',null,null,null);
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_JP_TI_TE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_JP_TI_TE_PK" ON "OASIS4"."WEBSERV_REF_JP_TI_TE" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_JP_TI_TE
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_JP_TI_TE" ADD CONSTRAINT "WEBSERV_REF_JP_TI_TE_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
