--------------------------------------------------------
-- Archivo creado  - lunes-marzo-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REF_PRE_TP_NU
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REF_PRE_TP_NU" 
   (	"ID_TPNU" NUMBER, 
	"CODIGO" NUMBER, 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"HABILITADO_MIPRES" NUMBER, 
	"VERSION_MIPRES" NUMBER(38,3), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;

   COMMENT ON TABLE "OASIS4"."WEBSERV_REF_PRE_TP_NU"  IS 'Tipo de productos nutricionales';
REM INSERTING into OASIS4.WEBSERV_REF_PRE_TP_NU
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('1','1101','Sustitutos de comidas intermedias - 75 a 150 kcal no deben sobrepasar las 1200 kcal al día.','0','1',to_date('23/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('2','1102','Sustitutos de una comida principal - 150 a 300 kcal no deben sobrepasar las 1200 kcal al día.','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('3','1201','Aminoácidos libres','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('4','1301','Proteína hidrolizada Basadas en Péptidos','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('5','1302','Proteína Parcialmente hidrolizada','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('6','1401','Diabetes - Baja carga de carbohidratos','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('7','1402','Diabetes - Cantidad permitida de Fructosa = 60g/día','0','1',to_date('23/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('8','1403','DNT Aguda - F75 Formula lactea de realimentación 75Kc/100ml.','0','1',to_date('23/01/17','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('9','1404','DNT Aguda - FTLC Formula terapeutica lista para el consumo 500kc/92g.','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('10','1405','Estrés Metabólico - Altas en péptidos y  antioxidantes y modificadas en hidratos de carbono y lípidos.','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('11','1406','Hepática - Alto en aminoácidos de cadena ramificada, bajo en aminoácidos aromáticos','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('12','1407','Inmuno moduladoras - Arginina, glutamina, ¿3 ácidos grasos, nucleótidos y antioxidantes.','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('13','1408','Pulmonar - Alto aporte de proteína y moderado aporte en grasa.','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('14','1409','Renal Diálisis - Alta en proteína y modificada en micronutrientes para neutralizar pérdidas por diálisis.','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('15','1410','Renal Prediálisis - Estadios 2,3,4 Baja en proteína, fósforo y electrolitos.','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('16','1411','Enfermedades del sistema nervioso','1','1',to_date('03/05/18','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('17','1501','Alta en Proteína - Proteína mayor al 20% de la energía total','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('18','1502','Con Fibra - 5 a 15 g/L','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('19','1503','Densidad Calórica - 1 a 2 kcal/mL','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('20','1504','Estándar - Distribución normal de la dieta','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('21','1601','Modulos de proteina, carbohidratos, lipidos','1','1',to_date('18/11/16','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REF_PRE_TP_NU (ID_TPNU,CODIGO,DESCRIPCION,HABILITADO_MIPRES,VERSION_MIPRES,FECHA) values ('22','1701','Fórmulas especiales para niños (lactantes, niños de corta edad y niños)','1','1',to_date('18/11/16','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index WEBSERV_REF_PRE_TP_NU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_REF_PRE_TP_NU_PK" ON "OASIS4"."WEBSERV_REF_PRE_TP_NU" ("ID_TPNU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  DDL for Index REF_PRE_TP_NU_CODIGO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."REF_PRE_TP_NU_CODIGO_UK1" ON "OASIS4"."WEBSERV_REF_PRE_TP_NU" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REF_PRE_TP_NU
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TP_NU" MODIFY ("ID_TPNU" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TP_NU" ADD CONSTRAINT "WEBSERV_REF_PRE_TP_NU_PK" PRIMARY KEY ("ID_TPNU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REF_PRE_TP_NU" ADD CONSTRAINT "REF_PRE_TP_NU_CODIGO_UK1" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
