--------------------------------------------------------
-- Archivo creado  - jueves-enero-23-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_PRES_DISP
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_PRES_DISP" 
   (	"ID_DISP" NUMBER, 
	"ID_PRES" NUMBER, 
	"CONORDEN" NUMBER, 
	"TIPOPREST" NUMBER, 
	"CAUSAS1" NUMBER, 
	"CODDISP" VARCHAR2(2000 BYTE), 
	"CANFORM" VARCHAR2(2000 BYTE), 
	"CADAFREUSO" VARCHAR2(2000 BYTE), 
	"CODFREUSO" VARCHAR2(2000 BYTE), 
	"CANT" VARCHAR2(2000 BYTE), 
	"CODPERDURTRAT" NUMBER, 
	"CANTTOTAL" VARCHAR2(2000 BYTE), 
	"JUSTNOPBS" VARCHAR2(2000 BYTE), 
	"INDREC" VARCHAR2(2000 BYTE), 
	"ESTJM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
REM INSERTING into OASIS4.WEBSERV_PRES_DISP
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_PRES_DISP (ID_DISP,ID_PRES,CONORDEN,TIPOPREST,CAUSAS1,CODDISP,CANFORM,CADAFREUSO,CODFREUSO,CANT,CODPERDURTRAT,CANTTOTAL,JUSTNOPBS,INDREC,ESTJM) values ('21','14027','1','2','1','044','30','30','5','30','5','30','paciente  portador  de  dos colostomia que  amerita  barrera   bolssas de colostomia 70 mm  ',' BARRERA  y BOLSAS DE COLOSTOMIA 70 MM  ','1');
Insert into OASIS4.WEBSERV_PRES_DISP (ID_DISP,ID_PRES,CONORDEN,TIPOPREST,CAUSAS1,CODDISP,CANFORM,CADAFREUSO,CODFREUSO,CANT,CODPERDURTRAT,CANTTOTAL,JUSTNOPBS,INDREC,ESTJM) values ('22','14119','1','1','1','044','1','1','8',null,null,'1','OCULOPLASTICA PACIENTE REMITIDA POR PRESENTAR OJO CIEGO DOLOROSO EN OJO DERECHO CON ANTECEDENTES DE GLAUCOMA CONGENITO. AL EXAMEN AVL OD: NPL. ENOFTALMOS GRADO I, PTOSIS GRADO I, CORNEA BLANCA Y OPACA EN 360 GRADOS. TAC DE ORBITAS SIMPLE: ENOFTALMOS DERECHO CON PTISIS BULBI, EN OI: CAMBIOS QX POR CX DE RETINA. CONTROL CON RESULTADOS. PLAN: LENTE DE CONTACTO COSMOPROTESICO EN OJO DERECHO','SE SOLICITA LENTE DE CONTACTO COSMOPROTESICO EN OJO DERECHO','1');
Insert into OASIS4.WEBSERV_PRES_DISP (ID_DISP,ID_PRES,CONORDEN,TIPOPREST,CAUSAS1,CODDISP,CANFORM,CADAFREUSO,CODFREUSO,CANT,CODPERDURTRAT,CANTTOTAL,JUSTNOPBS,INDREC,ESTJM) values ('1','797','1','1','1','044','1','1','8',null,null,'1','PACIENTE OPERADO DE EVISCERACION Y ENUCLEACION DEL GLOBO OCULAR DEL OJO IZQUIERDO POR FUERTE INFECCIÓN Y PERFORACIÓN DE LA CORNEA','SE ORDENA ADAPTACIÓN DE PRÓTESIS OCULAR PARA EVITAR CIERRE DE LA CAVIDAD ORBITARIA Y MEJORAR EL ASPECTO F�?SICO Y PSICOLÓGICO','1');
Insert into OASIS4.WEBSERV_PRES_DISP (ID_DISP,ID_PRES,CONORDEN,TIPOPREST,CAUSAS1,CODDISP,CANFORM,CADAFREUSO,CODFREUSO,CANT,CODPERDURTRAT,CANTTOTAL,JUSTNOPBS,INDREC,ESTJM) values ('2','1700','1','1','1','044','1','1','6','1','6','1','mejorar calidad de vida del paciente para poder deambular','protesis miembro pelvica derecha hasta la rodilla','1');
Insert into OASIS4.WEBSERV_PRES_DISP (ID_DISP,ID_PRES,CONORDEN,TIPOPREST,CAUSAS1,CODDISP,CANFORM,CADAFREUSO,CODFREUSO,CANT,CODPERDURTRAT,CANTTOTAL,JUSTNOPBS,INDREC,ESTJM) values ('3','3378','1','1','1','044','1','1','8',null,null,'1','PACIENTE REMITIDO X PRESENTAR CAIDA DE PARPADO SUPERIOR EN IZQ ASOCIADO A PTISIS BULBI, EL PACIENTE MANIFIESTA QUE QUIERE MEJORAR EL COLOR DEL OJO IZQUIERDO. ANT: CIRUGIA DE RETINA EN OI HACE 3 AÑOS DE EVOLUCIÓN. AL EXAMEN PARPADOS CON CAMBIOS SENILES. EN OI: PTISIS BULBI CON CORNEA OPACA Y BLANCA. PLAN: LENTE DE CONTACTO COSMOPROTESICO PUPILA NEGRA EN OJO IZQUIERDO. SU USO OFRECE UN MEJOR CONFORT A LOS PACIENTES CON ENFERMEDADES CORNEALES, LO QUE PERMITE UNA R�?PIDA EPITELIZACIÓN Y DESAPARICIÓN ','SE SOLICITA LENTE DE CONTACTO COSMOPROTESICO PARA OJO IZQUIERDO','1');
Insert into OASIS4.WEBSERV_PRES_DISP (ID_DISP,ID_PRES,CONORDEN,TIPOPREST,CAUSAS1,CODDISP,CANFORM,CADAFREUSO,CODFREUSO,CANT,CODPERDURTRAT,CANTTOTAL,JUSTNOPBS,INDREC,ESTJM) values ('4','3402','1','1','1','044','1','1','8',null,null,'1','se prescribe formula ÓPTICA permanente por un lente de contacto SE PROGRAMA CONSULTA DE OPTOMETRIA PARA ADAPTACIÓN DE LC TERAPÉUTICO Ojo izquierdo por cirugia de pterigion y cataratas','se realizara procedimiento de COLOCACIÓN del lente de contacto TERAPÉUTICO en el PRÓXIMO control.','1');
Insert into OASIS4.WEBSERV_PRES_DISP (ID_DISP,ID_PRES,CONORDEN,TIPOPREST,CAUSAS1,CODDISP,CANFORM,CADAFREUSO,CODFREUSO,CANT,CODPERDURTRAT,CANTTOTAL,JUSTNOPBS,INDREC,ESTJM) values ('5','4389','1','1','1','044','1','1','8',null,null,'1','PACIENTE REMITIDO CON ANT MEJORIA DE VISION EN OJO DERECHO, PERDIDA VISUAL EN OJO IZQUIERDO. CURSANDO CON NISTAGMUS HACE AÑOS Y REMITEN PARA MANEJO DE LA PERDIDA VISUAL EN OJO IZQUIERDO. REFIERE ARDOR Y MOLESTIAS OCULARE. AL EXAMEN EN AO: NISTAGMUS, EN OD: CORNEA TRANSPARENTE, PUPILA CORECTOPICA, EN OI: LECUOMA EN TODO EL EJE VISUAL, CORNEA BLANCA. PLAN: LENTE DE CONTACTO COSMOPROTESICO EN OJO IZQUIERDO. SE BUSCA MEJORAR LA APRIENCIA ESTETICA DEL OJO QUE SE VEN GRISES O BLANCO, DANDO MEJOR APARI','SE SOLICITA LENTE  DE CONTACTO COSMOPROTESICO PARA OJO IZQUIERDO ','1');
Insert into OASIS4.WEBSERV_PRES_DISP (ID_DISP,ID_PRES,CONORDEN,TIPOPREST,CAUSAS1,CODDISP,CANFORM,CADAFREUSO,CODFREUSO,CANT,CODPERDURTRAT,CANTTOTAL,JUSTNOPBS,INDREC,ESTJM) values ('6','4444','1','1','1','044','2','1','8',null,null,'1','PCTE REQUIERE BAJA VISION DEBIDO A DAÑO AVANZADO EN AO POR EL GLAUCOMA. por lo cual no REQUIERE DE OPTOMETRIA NORMAL, y se hace necesario la utilización de este tipo de lentes.\n','DOS PARES DE LENTES \nOD: LENTE ZEISS F540-VP ALTO INDICE 1.67 A.R  OI:LENTE ZEISS F540- VP ALTO INDICE 1.67 A.R','1');
--------------------------------------------------------
--  DDL for Index WEBSERV_PRES_DISP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."WEBSERV_PRES_DISP_PK" ON "OASIS4"."WEBSERV_PRES_DISP" ("ID_DISP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_PRES_DISP
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_PRES_DISP" MODIFY ("ID_DISP" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_PRES_DISP" ADD CONSTRAINT "WEBSERV_PRES_DISP_PK" PRIMARY KEY ("ID_DISP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEBSERV_PRES_DISP
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_PRES_DISP" ADD CONSTRAINT "PRES_DISP_ID_PRES_FK" FOREIGN KEY ("ID_PRES")
	  REFERENCES "OASIS4"."WEBSERV_PRES_PRES" ("ID_PRES") ENABLE;
