
CREATE TABLE "OASIS4"."WEBSERV_JUNTA_PROFESIONAL"
(
	"ID_JUPR" NUMBER NOT NULL ,
	"REPO_PERIODO"	DATE,
    "REPO_SERV_ID"	NUMBER(11,0),
    "REPO_TIRE_ID"	NUMBER(11,0),
	"NOPRESCRIPCION" VARCHAR2(500),
	"FPRESCRIPCION" DATE,
	"TIPOTECNOLOGIA" VARCHAR2(500),
	"CONSECUTIVO" NUMBER,
	"ESTJM" NUMBER,
	"CODENTPROC" VARCHAR2(500),
	"OBSERVACIONES" VARCHAR2(500),
	"JUSTIFICACIONTECNICA" VARCHAR2(500),
	"MODALIDAD" NUMBER,
	"NOACTA" VARCHAR2(500),
	"FECHAACTA" DATE,
	"FPROCESO" VARCHAR2(500),
	"TIPOIDPACIENTE" VARCHAR2(500),
	"NROIDPACIENTE" VARCHAR2(500),
	"CODENTJM" VARCHAR2(500),
	CONSTRAINT "WEBSERV_JUNTA_PROFESIONAL_PK" PRIMARY KEY ("ID_JUPR"),
	CONSTRAINT "JP_REPORTES_JSON_FK" FOREIGN KEY ("REPO_SERV_ID", "REPO_TIRE_ID", "REPO_PERIODO")
	  REFERENCES "OASIS4"."WEBSERV_REPORTES_JSON" ("SERV_ID", "TIRE_ID", "PERIODO")
);

CREATE INDEX "OASIS4"."_WEBSERV_JP_NOPRESCRPCION_UK" ON "OASIS4"."WEBSERV_JUNTA_PROFESIONAL"
("NOPRESCRIPCION");



 create sequence SEQ_WEBSERV_JUNTA_PROFESIONAL
  start with 1
  increment by 1
  maxvalue 9999999
  minvalue 1;
