--------------------------------------------------------
-- Archivo creado  - jueves-enero-23-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_PRES_INDI_UNIRS
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_PRES_INDI_UNIRS" 
   (	"ID_IMUN" NUMBER, 
	"ID_MEDI" NUMBER, 
	"CONORDEN" NUMBER, 
	"CODINDICACION" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
REM INSERTING into OASIS4.WEBSERV_PRES_INDI_UNIRS
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('55','3961','1','110');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('56','4055','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('57','4115','1','57');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('58','4122','1','142');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('59','4331','1','140');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('60','4437','1','160');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('61','4482','1','18');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('62','4631','1','124');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('63','4719','1','124');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('64','4739','1','23');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('65','4757','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('66','4821','1','131');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('67','5019','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('68','5022','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('69','5085','1','6');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('70','5135','2','98');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('71','5139','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('72','5220','1','137');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('73','5257','1','142');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('74','5333','1','137');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('75','6341','1','117');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('76','6345','1','126');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('77','6382','1','124');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('78','6389','1','126');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('79','6403','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('80','6432','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('81','6433','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('82','6458','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('83','6727','1','120');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('84','6782','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('85','6862','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('86','7045','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('381','21341','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('382','21455','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('141','10769','1','152');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('281','19181','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('282','19447','1','6');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('283','19557','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('284','19699','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('361','21038','1','117');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('362','21175','1','84');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('363','21196','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('1','377','1','108');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('2','416','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('3','493','1','84');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('4','501','1','84');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('161','11146','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('162','11250','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('163','11429','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('164','11583','1','149');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('165','11639','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('166','11640','2','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('167','11721','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('168','11927','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('169','12039','2','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('170','12133','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('171','12138','1','40');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('265','18834','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('266','18932','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('267','19061','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('21','673','1','111');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('22','707','1','111');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('23','879','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('24','942','1','84');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('25','962','1','84');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('26','1046','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('27','1132','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('28','1193','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('29','1242','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('30','1371','1','98');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('31','1445','1','124');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('32','1453','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('33','1473','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('34','1474','2','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('35','2131','1','40');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('36','2168','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('37','2175','1','114');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('38','2216','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('39','2222','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('40','2282','1','22');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('41','2352','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('42','2353','1','160');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('43','2458','1','160');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('44','2598','1','73');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('45','2729','1','160');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('46','2834','1','149');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('47','2976','1','114');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('48','3015','1','40');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('49','3141','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('50','3170','1','160');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('51','3369','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('52','3426','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('53','3612','1','152');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('54','3645','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('130','10035','1','91');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('131','10125','1','99');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('132','10277','1','99');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('172','12593','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('173','12642','1','143');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('174','12699','1','93');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('175','12699','1','77');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('176','12707','1','110');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('177','13008','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('178','13137','1','69');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('179','13256','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('180','13461','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('181','13535','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('182','13546','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('183','13584','1','160');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('184','13677','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('185','13712','1','85');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('186','13750','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('187','13767','1','142');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('212','14626','1','40');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('221','14804','1','85');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('222','14916','1','98');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('223','15239','1','156');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('224','15388','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('225','15404','1','156');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('226','15547','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('227','15638','1','99');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('228','15741','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('229','15746','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('230','15837','1','160');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('231','15868','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('232','15893','1','142');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('233','15933','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('234','16430','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('235','16691','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('236','16823','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('237','17077','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('238','17265','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('323','20283','2','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('341','20650','1','87');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('342','20686','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('321','20200','1','161');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('322','20282','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('101','7480','1','110');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('102','7524','1','150');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('103','7571','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('104','7572','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('105','7703','1','142');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('106','7706','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('107','7782','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('108','7965','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('109','7983','1','8');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('110','8016','1','87');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('111','8044','1','84');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('112','8232','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('113','8233','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('114','8588','1','76');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('115','8594','1','98');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('116','8693','1','106');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('117','8730','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('118','8786','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('119','8996','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('120','8997','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('121','9025','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('122','9153','1','70');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('123','9256','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('124','9266','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('125','9543','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('126','9557','1','111');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('127','9603','1','85');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('128','9907','1','160');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('129','9946','1','153');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('201','14113','1','124');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('202','14138','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('203','14234','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('204','14370','1','96');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('205','14413','1','2');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('206','14416','1','69');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('207','14417','1','69');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('208','14418','1','122');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('209','14423','1','13');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('210','14423','1','6');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('211','14533','1','51');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('261','18295','1','6');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('262','18445','1','6');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('263','18459','1','161');
Insert into OASIS4.WEBSERV_PRES_INDI_UNIRS (ID_IMUN,ID_MEDI,CONORDEN,CODINDICACION) values ('301','19962','1','70');
--------------------------------------------------------
--  DDL for Index PRES_INDI_UNIRS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."PRES_INDI_UNIRS_PK" ON "OASIS4"."WEBSERV_PRES_INDI_UNIRS" ("ID_IMUN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_PRES_INDI_UNIRS
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_PRES_INDI_UNIRS" MODIFY ("ID_IMUN" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_PRES_INDI_UNIRS" ADD CONSTRAINT "PRES_INDI_UNIRS_PK" PRIMARY KEY ("ID_IMUN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEBSERV_PRES_INDI_UNIRS
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_PRES_INDI_UNIRS" ADD CONSTRAINT "PRES_INDI_UNIRS_ID_MEDI_FK" FOREIGN KEY ("ID_MEDI")
	  REFERENCES "OASIS4"."WEBSERV_PRES_MEDI" ("ID_MEDI") ENABLE;
