--------------------------------------------------------
-- Archivo creado  - jueves-enero-23-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBSERV_REPORTES_JSON
--------------------------------------------------------

  CREATE TABLE "OASIS4"."WEBSERV_REPORTES_JSON" 
   (	"SERV_ID" NUMBER(11,0), 
	"TIRE_ID" NUMBER(11,0), 
	"PERIODO" DATE, 
	"JSON" CLOB, 
	"FECHA_ACTUALIZACION" DATE DEFAULT sysdate, 
	"FECHA_REGISTRO" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" 
 LOB ("JSON") STORE AS SECUREFILE (
  TABLESPACE "OASIS4" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into OASIS4.WEBSERV_REPORTES_JSON
SET DEFINE OFF;
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('31/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('31/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('01/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('02/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('03/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('04/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('05/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('06/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('07/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('12/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('16/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('09/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('11/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('13/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('14/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('10/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('17/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('18/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('19/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/01/20','DD/MM/RR'),to_date('23/01/20','DD/MM/RR'),to_date('23/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('22/01/20','DD/MM/RR'),to_date('23/01/20','DD/MM/RR'),to_date('23/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('31/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('08/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('20/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('31/01/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/02/19','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'),to_date('15/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('15/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'),to_date('17/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','1',to_date('21/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'),to_date('22/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/02/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('31/03/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/04/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/05/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/09/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/06/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('31/07/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/08/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('27/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('31/10/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('03/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('04/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('11/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('12/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('18/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('23/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('28/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('29/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('30/11/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('01/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('02/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('05/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('06/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('07/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('08/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('09/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('10/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('13/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('14/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('15/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('16/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('17/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('19/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('20/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('21/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('22/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('24/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('25/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
Insert into OASIS4.WEBSERV_REPORTES_JSON (SERV_ID,TIRE_ID,PERIODO,FECHA_ACTUALIZACION,FECHA_REGISTRO) values ('3','2',to_date('26/12/19','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'),to_date('16/01/20','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index PK_WEBSERV_REPORTES_JSON
--------------------------------------------------------

  CREATE UNIQUE INDEX "OASIS4"."PK_WEBSERV_REPORTES_JSON" ON "OASIS4"."WEBSERV_REPORTES_JSON" ("SERV_ID", "TIRE_ID", "PERIODO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4" ;
--------------------------------------------------------
--  Constraints for Table WEBSERV_REPORTES_JSON
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REPORTES_JSON" MODIFY ("SERV_ID" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REPORTES_JSON" MODIFY ("TIRE_ID" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REPORTES_JSON" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "OASIS4"."WEBSERV_REPORTES_JSON" ADD CONSTRAINT "PK_WEBSERV_REPORTES_JSON" PRIMARY KEY ("SERV_ID", "TIRE_ID", "PERIODO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OASIS4"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEBSERV_REPORTES_JSON
--------------------------------------------------------

  ALTER TABLE "OASIS4"."WEBSERV_REPORTES_JSON" ADD CONSTRAINT "FK_WEBSERV_REPORTES_JSON1" FOREIGN KEY ("SERV_ID")
	  REFERENCES "OASIS4"."WEBSERV_SERVICIOS" ("SERV_ID") ENABLE;
  ALTER TABLE "OASIS4"."WEBSERV_REPORTES_JSON" ADD CONSTRAINT "FK_WEBSERV_REPORTES_JSON2" FOREIGN KEY ("TIRE_ID")
	  REFERENCES "OASIS4"."WEBSERV_TIPOREPORTES" ("TIRE_ID") ENABLE;
