SELECT 
  JP.ID_JUPR,
  JP.REPO_PERIODO,
  JP.REPO_SERV_ID,
  JP.REPO_TIRE_ID,
  JP.NOPRESCRIPCION,
  JP.FPRESCRIPCION,
  DECODE(JP.TIPOTECNOLOGIA,NULL,'NO EXISTE',JP.TIPOTECNOLOGIA)TIPOTECNOLOGIA,------
  DECODE(TT.DESCRIPCION,NULL,'NO EXISTE',TT.DESCRIPCION)DESC_TIPOTECNOLOGIA,
  DECODE(JP.CONSECUTIVO,NULL,'NO EXISTE',JP.CONSECUTIVO)CONSECUTIVO,
  DECODE(JP.ESTJM,NULL,'NO EXISTE',JP.ESTJM)ESTJM,------
  DECODE(EJ.DESCRIPCION,NULL,'NO EXISTE',EJ.DESCRIPCION)DESC_ESTJM,
  DECODE(JP.CODENTPROC,NULL,'NO EXISTE',JP.CODENTPROC)CODENTPROC,
  DECODE(JP.OBSERVACIONES,NULL,'NO EXISTE',JP.OBSERVACIONES)OBSERVACIONES,
  DECODE(JP.JUSTIFICACIONTECNICA,NULL,'NO EXISTE',JP.JUSTIFICACIONTECNICA)JUSTIFICACIONTECNICA,
  DECODE(JP.MODALIDAD,NULL,'NO EXISTE',JP.MODALIDAD)MODALIDAD,--------
  DECODE(MO.DESCRIPCION,NULL,'NO EXISTE',MO.DESCRIPCION)DESC_MODALIDAD,
  DECODE(JP.NOACTA,NULL,'NO EXISTE',JP.NOACTA)NOACTA,
  DECODE(JP.FECHAACTA,NULL,'NO EXISTE',JP.FECHAACTA)FECHAACTA,
  DECODE(JP.FPROCESO,NULL,'NO EXISTE',JP.FPROCESO)FPROCESO,
  DECODE(JP.TIPOIDPACIENTE,NULL,'NO EXISTE',JP.TIPOIDPACIENTE)TIPOIDPACIENTE,-------
  DECODE (TA.DESCRIPCION,NULL,'NO EXISTE',TA.DESCRIPCION)DESC_TIPOIDPACIENTE,
  DECODE(JP.NROIDPACIENTE,NULL,'NO EXISTE',JP.NROIDPACIENTE)NROIDPACIENTE,
  DECODE(JP.CODENTJM,NULL,'NO EXISTE',JP.CODENTJM)CODENTJM
FROM WEBSERV_JUNTA_PROFESIONAL JP 
LEFT JOIN WEBSERV_REF_JP_TI_TE  TT ON JP.TIPOTECNOLOGIA=TT.CODIGO
LEFT JOIN WEBSERV_REF_PRE_ES_JP EJ ON JP.ESTJM=EJ.CODIGO
LEFT JOIN WEBSERV_REF_JP_MODAL  MO ON JP.MODALIDAD=MO.CODIGO
LEFT JOIN WEBSERV_REF_PRE_TD_AA TA ON JP.TIPOIDPACIENTE=TA.CODIGO 
where  JP.REPO_SERV_ID=9 and JP.REPO_TIRE_ID=2 and JP.REPO_PERIODO BETWEEN '01/01/2019' AND '01/02/2019';
