/*Consultar los json que se registraron con errores: estose sabe porque todos los datos del campo WEBSERV_REPORTES_JSON.json
que tengan 'SI' deben tener datos en la tabla  WEBSERV_PRES_PRES, de no ser asi se entiende que hay un error*/
SELECT 
  RJ.PERIODO,
  RJ.SERV_ID,
  SE.NOMBRE,
  RJ.TIRE_ID,
  TR.NOMBRE,
  RJ.JSON,
  PP.*
FROM WEBSERV_REPORTES_JSON RJ
JOIN WEBSERV_SERVICIOS SE ON SE.SERV_ID= RJ.SERV_ID
JOIN WEBSERV_TIPOREPORTES TR ON TR.TIRE_ID=RJ.TIRE_ID
LEFT JOIN WEBSERV_PRES_PRES PP ON 
  PP.REPO_PERIODO=RJ.PERIODO
  AND PP.REPO_SERV_ID=RJ.SERV_ID
  AND PP.REPO_TIRE_ID=RJ.TIRE_ID
  WHERE dbms_lob.substr(JSON)='SI' AND PP.REPO_PERIODO IS NULL AND PERIODO>='01/01/20' AND RJ.SERV_ID=3
  ORDER BY RJ.PERIODO DESC,RJ.SERV_ID DESC;
  
 SELECT * FROM WEBSERV_REPORTES_JSON RJ
where  RJ.SERV_ID=:REPO_SERV_ID and RJ.TIRE_ID=:REPO_TIRE_ID and RJ.PERIODO BETWEEN :PERIODO_INICIAL AND :PERIODO_FINAL;

  
  
  
 /*Borrar Json
 DELETE
FROM WEBSERV_REPORTES_JSON
WHERE SERV_ID           = 3
AND TIRE_ID             = 1
AND PERIODO             in ('07/04/20','19/03/20','16/03/20');
  
 */ 
 
 
 