--Referencias
/*
DROP TABLE WEBSERV_REF_PRE_AMB_ATE;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_AMB_ATE;
DROP TABLE WEBSERV_REF_PRE_ENF_UER;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_ENF_UER;
DROP TABLE WEBSERV_REF_PRE_CIE_10;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_CIE_10;
DROP TABLE WEBSERV_REF_PRE_TI_TR;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TI_TR;
DROP TABLE WEBSERV_REF_PRE_TI_ME;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TI_ME;
DROP TABLE WEBSERV_REF_PRE_TI_PR;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TI_PR;
DROP TABLE WEBSERV_REF_PRE_FO_FA;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_FO_FA;
DROP TABLE WEBSERV_REF_PRE_VI_AD;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_VI_AD;
DROP TABLE WEBSERV_REF_PRE_UN_ME;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_UN_ME;
DROP TABLE WEBSERV_REF_PRE_TIEMPOS;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TIEMPOS;
DROP TABLE WEBSERV_REF_PRE_IN_ES;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_IN_ES;
DROP TABLE WEBSERV_REF_PRE_UF_CT;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_UF_CT;
DROP TABLE WEBSERV_REF_PRE_ES_JP;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_ES_JP;
*/

/*
DELETE FROM WEBSERV_REF_PRE_AMB_ATE;
DELETE FROM WEBSERV_REF_PRE_ENF_UER;
DELETE FROM WEBSERV_REF_PRE_CIE_10;
DELETE FROM WEBSERV_REF_PRE_TI_TR;
DELETE FROM WEBSERV_REF_PRE_TI_ME;
DELETE FROM WEBSERV_REF_PRE_TI_PR;
DELETE FROM WEBSERV_REF_PRE_FO_FA;
DELETE FROM WEBSERV_REF_PRE_VI_AD;
DELETE FROM WEBSERV_REF_PRE_UN_ME;
DELETE FROM WEBSERV_REF_PRE_TIEMPOS;
DELETE FROM WEBSERV_REF_PRE_IN_ES;
DELETE FROM WEBSERV_REF_PRE_UF_CT;
DELETE FROM WEBSERV_REF_PRE_ES_JP;*/



SELECT * FROM WEBSERV_REF_PRE_AMB_ATE;
SELECT * FROM WEBSERV_REF_PRE_ENF_UER;
SELECT * FROM WEBSERV_REF_PRE_CIE_10;
SELECT * FROM WEBSERV_REF_PRE_TI_TR;
SELECT * FROM WEBSERV_REF_PRE_TI_ME;
SELECT * FROM WEBSERV_REF_PRE_TI_PR;
SELECT * FROM WEBSERV_REF_PRE_FO_FA;
SELECT * FROM WEBSERV_REF_PRE_VI_AD;
SELECT * FROM WEBSERV_REF_PRE_UN_ME;
SELECT * FROM WEBSERV_REF_PRE_TIEMPOS;
SELECT * FROM WEBSERV_REF_PRE_IN_ES;
SELECT * FROM WEBSERV_REF_PRE_UF_CT;
SELECT * FROM WEBSERV_REF_PRE_ES_JP;






---------------------Conultas generales de tablas de prescripcion-----------------------------------------------------
/*
DROP TABLE WEBSERV_PRES_SERV_COMP;
DROP SEQUENCE SEQ_WEBSERV_PRES_SERV_COMP;
DROP TABLE WEBSERV_PRES_PROD_NUTR;
DROP SEQUENCE SEQ_WEBSERV_PRES_PROD_NUTR;
DROP TABLE WEBSERV_PRES_DISP;
DROP SEQUENCE SEQ_WEBSERV_PRES_DISP;
DROP TABLE WEBSERV_PRES_PROC;
DROP SEQUENCE SEQ_WEBSERV_PRES_PROC;
DROP TABLE WEBSERV_PRES_PRIN_ACTI;
DROP SEQUENCE SEQ_WEBSERV_PRES_PRIN_ACTI;
DROP TABLE WEBSERV_PRES_INDI_UNIRS;
DROP SEQUENCE SEQ_WEBSERV_PRES_INDI_UNIRS;
DROP TABLE WEBSERV_PRES_MEDI;
DROP SEQUENCE SEQ_WEBSERV_PRES_MEDI;
DROP TABLE WEBSERV_PRES_PRES;
DROP SEQUENCE SEQ_WEBSERV_PRES_PRES;
*/

DELETE FROM WEBSERV_PRES_SERV_COMP;
DELETE FROM WEBSERV_PRES_PROD_NUTR;
DELETE FROM WEBSERV_PRES_DISP;
DELETE FROM WEBSERV_PRES_PROC;
DELETE FROM WEBSERV_PRES_PRIN_ACTI;
DELETE FROM WEBSERV_PRES_INDI_UNIRS;
DELETE FROM WEBSERV_PRES_MEDI;
DELETE FROM WEBSERV_PRES_PRES;

SELECT * FROM WEBSERV_PRES_SERV_COMP;
SELECT * FROM WEBSERV_PRES_PROD_NUTR;
SELECT * FROM WEBSERV_PRES_DISP;
SELECT * FROM WEBSERV_PRES_PROC;
SELECT * FROM WEBSERV_PRES_INDI_UNIRS;
SELECT * FROM WEBSERV_PRES_PRIN_ACTI;
SELECT * FROM WEBSERV_PRES_MEDI ORDER BY id_medi;
SELECT * FROM WEBSERV_PRES_PRES ORDER BY id_pres;



SELECT * FROM WEBSERV_PRES_PRES PP
LEFT JOIN WEBSERV_PRES_MEDI  PM ON PM.ID_PRES=PP.ID_PRES
WHERE PP.NOPRESCRIPCION='20191029146015264609'
ORDER BY id_medi;
SELECT * FROM WEBSERV_PRES_PRES ORDER BY id_pres;


----------------------------------------------------------------
--Consultas de json unificado

/*Eliminar tablas
drop table webserv_log_errores;
drop table webserv_reportes_json;
drop table webserv_servicios;
DROP SEQUENCE SEQ_webserv_servicios;
drop table webserv_tiposervicios;
DROP SEQUENCE SEQ_webserv_tiposervicios;
drop table webserv_webservices;
DROP SEQUENCE SEQ_webserv_webservices;
drop table webserv_tiporeportes;
DROP SEQUENCE SEQ_webserv_tiporeportes;

*/

delete from webserv_reportes_json;
delete from webserv_log_errores;


select * from webserv_webservices;
select * from webserv_tiposervicios;
select * from webserv_servicios;
select * from webserv_tiporeportes;
select * from webserv_reportes_json;
select * from webserv_log_errores;



---------------------------------------------Consultas de pruebas
--Obtener Datos del servicio
SELECT S.URL, S.NOMBRE AS SERV_NOMBRE, TS.WS_ID
FROM WEBSERV_SERVICIOS S
JOIN WEBSERV_TIPOSERVICIOS TS ON S.TISE_ID   =TS.TISE_ID
WHERE S.SERV_ID=3;

--Obtener los datos
select NIT,TOKEN 
from WEBSERV_TIPOREPORTES 
WHERE TIRE_ID=1;

--Verificar si el periodo ya esta registrado
SELECT repo_periodo, repo_json 
FROM reportesws;

--Cantidad de registros
select count(1) CANTIDAD from WEBSERV_REPORTES_JSON 
where SERV_ID=3 and TIRE_ID=2 and PERIODO='29/10/2019';
