--Reporte general y de prescripciones
SELECT 
  ID_PRES,
  NOPRESCRIPCION,
  FPRESCRIPCION,
  HPRESCRIPCION,
  CODHABIPS,
  TIPOIDIPS,
  NROIDIPS,
  CODDANEMUNIPS,
  DIRSEDEIPS,
  TELSEDEIPS,
  TIPOIDPROF,
  NUMIDPROF,
  PNPROFS,
  SNPROFS,
  PAPROFS,
  SAPROFS,
  REGPROFS,
  TIPOIDPACIENTE,
  NROIDPACIENTE,
  PNPACIENTE,
  SNPACIENTE,
  PAPACIENTE,
  SAPACIENTE,

  DECODE(PP.CODAMBATE,null,'NO EXISTE',CODAMBATE) AS CODAMBATE,
  PAA.DESCRIPCION AS DESC_CODAMBATE,
  
  DECODE(PP.REFAMBATE,null,'NO EXISTE',REFAMBATE) AS REFAMBATE,
  DECODE(REFAMBATE,0,'NO',1,'SI','NO EXISTE') as DESC_REFAMBATE,
  
  DECODE(PP.ENFHUERFANA,null,'NO EXISTE',ENFHUERFANA) AS ENFHUERFANA,
  DECODE(ENFHUERFANA,0,'NO',1,'SI','NO EXISTE') as DESC_ENFHUERFANA,
  
  DECODE(CODENFHUERFANA,NULL,'NO EXISTE',CODENFHUERFANA) AS CODENFHUERFANA,
  DECODE(dbms_lob.substr( EH.DESCRIPCION, 4000, 1 ) ,NULL,'NO EXISTE') AS DESC_CODENFHUERFANA,
  
  DECODE(ENFHUERFANADX,NULL,'NO EXISTE',ENFHUERFANADX) AS ENFHUERFANADX,
  DECODE(ENFHUERFANADX,0,'NO',1,'SI','NO EXISTE') as DESC_ENFHUERFANADX,
  
  DECODE(CODDXPPAL,NULL,'NO EXISTE',CODDXPPAL) AS CODDXPPAL,--4. Lista(Prec-CIE-10)
  DECODE(dbms_lob.substr(CIE_CODDXPPAL.DESCRIPCION),NULL,'NO EXISTE',dbms_lob.substr(CIE_CODDXPPAL.DESCRIPCION)) AS DESC_CODDXPPAL, 
  --DECODE(dbms_lob.substr((SELECT DESCRIPCION FROM WEBSERV_REF_PRE_CIE_10 WHERE CODIGO=CODDXPPAL), 4000, 1 ),NULL,'NO EXISTE') AS DESC_CODDXPPAL,
  
  DECODE(CODDXREL1,NULL,'NO EXISTE',CODDXREL1) AS CODDXREL1,--4. Lista(Prec-CIE-10)
  DECODE(dbms_lob.substr(CIE_CODDXREL1.DESCRIPCION),NULL,'NO EXISTE',dbms_lob.substr(CIE_CODDXREL1.DESCRIPCION)) AS DESC_CODDXREL1,
  --DECODE(dbms_lob.substr((SELECT DESCRIPCION FROM WEBSERV_REF_PRE_CIE_10 WHERE CODIGO=CODDXREL1), 4000, 1 ),NULL,'NO EXISTE') AS DESC_CODDXREL1,
  
  DECODE(CODDXREL2,NULL,'NO EXISTE',CODDXREL2) AS CODDXREL2,--4. Lista(Prec-CIE-10)
  DECODE(dbms_lob.substr(CIE_CODDXREL2.DESCRIPCION),NULL,'NO EXISTE',dbms_lob.substr(CIE_CODDXREL2.DESCRIPCION)) AS DESC_CODDXREL2,
  --DECODE(dbms_lob.substr((SELECT DESCRIPCION FROM WEBSERV_REF_PRE_CIE_10 WHERE CODIGO=CODDXREL2), 4000, 1 ),NULL,'NO EXISTE') AS DESC_CODDXREL2,
  
  SOPNUTRICIONAL,
  CODEPS,
  TIPOIDMADREPACIENTE,
  NROIDMADREPACIENTE,
  TIPOTRANSC,--5 Lista(Presc-TipoTransc)
  DECODE(DBMS_LOB.SUBSTR(TT.DESCRIPCION),NULL,'NO EXISTE',DBMS_LOB.SUBSTR(TT.DESCRIPCION)) AS DESC_TIPOTRANSC,
  TIPOIDDONANTEVIVO,
  NROIDDONANTEVIVO,
  ESTPRES
FROM WEBSERV_PRES_PRES pp
LEFT JOIN WEBSERV_REF_PRE_AMB_ATE paa
ON paa.CODIGO=pp.CODAMBATE
LEFT JOIN WEBSERV_REF_PRE_ENF_UER EH ON EH.CODIGO=pp.CODENFHUERFANA
LEFT JOIN WEBSERV_REF_PRE_CIE_10 CIE_CODDXPPAL ON CIE_CODDXPPAL.CODIGO=PP.CODDXPPAL
LEFT JOIN WEBSERV_REF_PRE_CIE_10 CIE_CODDXREL1 ON CIE_CODDXREL1.CODIGO=PP.CODDXREL1
LEFT JOIN WEBSERV_REF_PRE_CIE_10 CIE_CODDXREL2 ON CIE_CODDXREL2.CODIGO=PP.CODDXREL2
LEFT JOIN WEBSERV_REF_PRE_TI_TR TT ON PP.TIPOTRANSC=TT.CODIGO
where  pp.REPO_SERV_ID=3 and pp.REPO_TISE_ID=2 and pp.REPO_PERIODO='01/01/2020';