--Referencias
/*
DROP TABLE WEBSERV_REF_PRE_AMB_ATE;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_AMB_ATE;
DROP TABLE WEBSERV_REF_PRE_ENF_UER;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_ENF_UER;
DROP TABLE WEBSERV_REF_PRE_CIE_10;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_CIE_10;
DROP TABLE WEBSERV_REF_PRE_TI_TR;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TI_TR;
DROP TABLE WEBSERV_REF_PRE_TI_ME;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TI_ME;
DROP TABLE WEBSERV_REF_PRE_TI_PR;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TI_PR;
DROP TABLE WEBSERV_REF_PRE_FO_FA;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_FO_FA;
DROP TABLE WEBSERV_REF_PRE_VI_AD;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_VI_AD;
DROP TABLE WEBSERV_REF_PRE_UN_ME;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_UN_ME;
DROP TABLE WEBSERV_REF_PRE_TIEMPOS;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TIEMPOS;
DROP TABLE WEBSERV_REF_PRE_IN_ES;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_IN_ES;
DROP TABLE WEBSERV_REF_PRE_UF_CT;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_UF_CT;
DROP TABLE WEBSERV_REF_PRE_ES_JP;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_ES_JP;
DROP TABLE WEBSERV_REF_PRE_IND_UNI;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_IND_UNI;
DROP TABLE WEBSERV_REF_PRE_CUPS;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_CUPS
DROP TABLE WEBSERV_REF_PRE_DIAG;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_DIAG;
DROP TABLE WEBSERV_REF_PRE_TP_NU;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TP_NU
DROP TABLE WEBSERV_REF_PRE_PR_NU;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_PR_NU;
DROP TABLE WEBSERV_REF_PRE_FP_NU;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_FP_NU;
DROP TABLE WEBSERV_REF_PRE_VA_PN;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_VA_PN;
DROP TABLE WEBSERV_REF_PRE_SC_PR;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_SC_PR;
DROP TABLE WEBSERV_REF_PRE_TI_TRANSPORTE;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TI_TRANSP;
DROP TABLE WEBSERV_REF_PRE_TD_AA;
DROP SEQUENCE SEQ_WEBSERV_REF_PRE_TD_AA;
DROP TABLE WEBSERV_REF_PRE_PA_AA;
DROP SEQUENCE WEBSERV_REF_PRE_PA_AA;
*/


/*
DELETE FROM WEBSERV_REF_PRE_AMB_ATE;
DELETE FROM WEBSERV_REF_PRE_ENF_UER;
DELETE FROM WEBSERV_REF_PRE_CIE_10;
DELETE FROM WEBSERV_REF_PRE_TI_TR;
DELETE FROM WEBSERV_REF_PRE_TI_ME;
DELETE FROM WEBSERV_REF_PRE_TI_PR;
DELETE FROM WEBSERV_REF_PRE_FO_FA;
DELETE FROM WEBSERV_REF_PRE_VI_AD;
DELETE FROM WEBSERV_REF_PRE_UN_ME;
DELETE FROM WEBSERV_REF_PRE_TIEMPOS;
DELETE FROM WEBSERV_REF_PRE_IN_ES;
DELETE FROM WEBSERV_REF_PRE_UF_CT;
DELETE FROM WEBSERV_REF_PRE_ES_JP;
DELETE FROM WEBSERV_REF_PRE_IND_UNI;
DELETE FROM WEBSERV_REF_PRE_CUPS;
DELETE FROM WEBSERV_REF_PRE_DIAG;
DELETE FROM WEBSERV_REF_PRE_TP_NU;
DELETE FROM WEBSERV_REF_PRE_PR_NU;
DELETE FROM WEBSERV_REF_PRE_FP_NU;
DELETE FROM WEBSERV_REF_PRE_VA_PN;
DELETE FROM WEBSERV_REF_PRE_SC_PR;
DELETE FROM WEBSERV_REF_PRE_TI_TRANSPORTE;
DELETE FROM WEBSERV_REF_PRE_TD_AA;
DELETE FROM WEBSERV_REF_PRE_PA_AA;*/



SELECT * FROM WEBSERV_REF_PRE_AMB_ATE;
SELECT * FROM WEBSERV_REF_PRE_ENF_UER;
SELECT * FROM WEBSERV_REF_PRE_CIE_10;
SELECT * FROM WEBSERV_REF_PRE_TI_TR;
SELECT * FROM WEBSERV_REF_PRE_TI_ME;
SELECT * FROM WEBSERV_REF_PRE_TI_PR;
SELECT * FROM WEBSERV_REF_PRE_FO_FA;
SELECT * FROM WEBSERV_REF_PRE_VI_AD;
SELECT * FROM WEBSERV_REF_PRE_UN_ME;
SELECT * FROM WEBSERV_REF_PRE_TIEMPOS;
SELECT * FROM WEBSERV_REF_PRE_IN_ES;
SELECT * FROM WEBSERV_REF_PRE_UF_CT;
SELECT * FROM WEBSERV_REF_PRE_ES_JP;
SELECT * FROM WEBSERV_REF_PRE_IND_UNI;
SELECT * FROM WEBSERV_REF_PRE_CUPS;
SELECT * FROM WEBSERV_REF_PRE_DIAG;
SELECT * FROM WEBSERV_REF_PRE_TP_NU;
SELECT * FROM WEBSERV_REF_PRE_PR_NU;
SELECT * FROM WEBSERV_REF_PRE_FP_NU;
SELECT * FROM WEBSERV_REF_PRE_VA_PN;
SELECT * FROM WEBSERV_REF_PRE_SC_PR;
SELECT * FROM WEBSERV_REF_PRE_TI_TRANSPORTE;
SELECT * FROM WEBSERV_REF_PRE_TD_AA;
SELECT * FROM WEBSERV_REF_PRE_PA_AA;


/*
update WEBSERV_REF_PRE_PA_AA set descripcion=REPLACE(descripcion,' ','') where CODIGO=1

update tabla set campo_a_actualizar=REPLACE(campo_a_actualizar,' ','') where campo_ce_la_condicion=condicion
*/




---------------------Conultas generales de tablas de prescripcion-----------------------------------------------------
/*
DROP TABLE WEBSERV_PRES_SERV_COMP;
DROP SEQUENCE SEQ_WEBSERV_PRES_SERV_COMP;
DROP TABLE WEBSERV_PRES_PROD_NUTR;
DROP SEQUENCE SEQ_WEBSERV_PRES_PROD_NUTR;
DROP TABLE WEBSERV_PRES_DISP;
DROP SEQUENCE SEQ_WEBSERV_PRES_DISP;
DROP TABLE WEBSERV_PRES_PROC;
DROP SEQUENCE SEQ_WEBSERV_PRES_PROC;
DROP TABLE WEBSERV_PRES_PRIN_ACTI;
DROP SEQUENCE SEQ_WEBSERV_PRES_PRIN_ACTI;
DROP TABLE WEBSERV_PRES_INDI_UNIRS;
DROP SEQUENCE SEQ_WEBSERV_PRES_INDI_UNIRS;
DROP TABLE WEBSERV_PRES_MEDI;
DROP SEQUENCE SEQ_WEBSERV_PRES_MEDI;
DROP TABLE WEBSERV_PRES_PRES;
DROP SEQUENCE SEQ_WEBSERV_PRES_PRES;
*/

DELETE FROM WEBSERV_PRES_SERV_COMP;
DELETE FROM WEBSERV_PRES_PROD_NUTR;
DELETE FROM WEBSERV_PRES_DISP;
DELETE FROM WEBSERV_PRES_PROC;
DELETE FROM WEBSERV_PRES_PRIN_ACTI;
DELETE FROM WEBSERV_PRES_INDI_UNIRS;
DELETE FROM WEBSERV_PRES_MEDI;
DELETE FROM WEBSERV_PRES_PRES;

SELECT * FROM WEBSERV_PRES_SERV_COMP;
SELECT * FROM WEBSERV_PRES_PROD_NUTR;
SELECT * FROM WEBSERV_PRES_DISP;
SELECT * FROM WEBSERV_PRES_PROC;
SELECT * FROM WEBSERV_PRES_INDI_UNIRS;
SELECT * FROM WEBSERV_PRES_PRIN_ACTI;
SELECT * FROM WEBSERV_PRES_MEDI ORDER BY id_medi;
SELECT * FROM WEBSERV_PRES_PRES ORDER BY id_pres;


--Consultar un periodo cargado
SELECT * FROM WEBSERV_PRES_PRES PP 
--WHERE PP.REPO_PERIODO='14/02/19';
WHERE pp.NOPRESCRIPCION='20200103157016578325';

--Medicamentos
SELECT PM.* FROM WEBSERV_PRES_MEDI PM 
join WEBSERV_PRES_PRES pp on PP.ID_PRES=PM.ID_PRES
WHERE pp.NOPRESCRIPCION='20190214169010446919';

SELECT IU.* FROM WEBSERV_PRES_INDI_UNIRS IU 
JOIN WEBSERV_PRES_MEDI PM ON PM.ID_MEDI=IU.ID_MEDI
JOIN WEBSERV_PRES_PRES pp on PP.ID_PRES=PM.ID_PRES
WHERE pp.NOPRESCRIPCION='20190214190010446167';

SELECT PPA.* FROM WEBSERV_PRES_PRIN_ACTI PPA
JOIN WEBSERV_PRES_MEDI PM ON PM.ID_MEDI=PPA.ID_MEDI
JOIN WEBSERV_PRES_PRES pp on PP.ID_PRES=PM.ID_PRES
WHERE pp.NOPRESCRIPCION='20190214190010446167';
--Medicamentos

SELECT SP.* FROM WEBSERV_PRES_SERV_COMP SP 
join WEBSERV_PRES_PRES pp on PP.ID_PRES=SP.ID_PRES
WHERE pp.NOPRESCRIPCION='20190214190010446167';

SELECT PN.* FROM WEBSERV_PRES_PROD_NUTR PN 
join WEBSERV_PRES_PRES pp on PP.ID_PRES=PN.ID_PRES
WHERE pp.NOPRESCRIPCION='20190214190010446167';

SELECT PD.* FROM WEBSERV_PRES_DISP PD 
join WEBSERV_PRES_PRES pp on PP.ID_PRES=PD.ID_PRES
WHERE pp.NOPRESCRIPCION='20190214190010446167';

SELECT PPR.* FROM WEBSERV_PRES_PROC PPR 
join WEBSERV_PRES_PRES pp on PP.ID_PRES=PPR.ID_PRES
WHERE pp.NOPRESCRIPCION='20190214190010446167';


----------------------------------------------------------------
--Consultas de json unificado

/*Eliminar tablas
drop table webserv_log_errores;
drop table webserv_reportes_json;
drop table webserv_servicios;
DROP SEQUENCE SEQ_webserv_servicios;
drop table webserv_tiposervicios;
DROP SEQUENCE SEQ_webserv_tiposervicios;
drop table webserv_webservices;
DROP SEQUENCE SEQ_webserv_webservices;
drop table webserv_tiporeportes;
DROP SEQUENCE SEQ_webserv_tiporeportes;

*/
/*
delete from webserv_reportes_json;
delete from webserv_log_errores;
*/

select * from webserv_webservices;
select * from webserv_tiposervicios;
select * from webserv_servicios;
select * from webserv_tiporeportes;


select * from webserv_reportes_json rj 
where  RJ.SERV_ID=3 --and RJ.TIRE_ID=2
AND dbms_lob.substr( rj.JSON)='NO' 
order by PERIODO desc;

select * from webserv_log_errores;
