/*
DROP TABLE WEBSERV_PRES_SERV_COMP;
DROP SEQUENCE SEQ_WEBSERV_PRES_SERV_COMP;
DROP TABLE WEBSERV_PRES_PROD_NUTR;
DROP SEQUENCE SEQ_WEBSERV_PRES_PROD_NUTR;
DROP TABLE WEBSERV_PRES_DISP;
DROP SEQUENCE SEQ_WEBSERV_PRES_DISP;
DROP TABLE WEBSERV_PRES_PROC;
DROP SEQUENCE SEQ_WEBSERV_PRES_PROC;
DROP TABLE WEBSERV_PRES_PRIN_ACTI;
DROP SEQUENCE SEQ_WEBSERV_PRES_PRIN_ACTI;
DROP TABLE WEBSERV_PRES_INDI_UNIRS;
DROP SEQUENCE SEQ_WEBSERV_PRES_INDI_UNIRS;
DROP TABLE WEBSERV_PRES_MEDI;
DROP SEQUENCE SEQ_WEBSERV_PRES_MEDI;
DROP TABLE WEBSERV_PRES_PRES;
DROP SEQUENCE SEQ_WEBSERV_PRES_PRES;
*/
SELECT * FROM WEBSERV_PRES_SERV_COMP;
SELECT * FROM WEBSERV_PRES_PROD_NUTR;
SELECT * FROM WEBSERV_PRES_DISP;
SELECT * FROM WEBSERV_PRES_PROC;
SELECT * FROM WEBSERV_PRES_INDI_UNIRS;
SELECT * FROM WEBSERV_PRES_PRIN_ACTI;
SELECT * FROM WEBSERV_PRES_MEDI ORDER BY id_medi;
SELECT * FROM WEBSERV_PRES_PRES ORDER BY id_pres;




DELETE FROM WEBSERV_PRES_SERV_COMP;
DELETE FROM WEBSERV_PRES_PROD_NUTR;
DELETE FROM WEBSERV_PRES_DISP;
DELETE FROM WEBSERV_PRES_PROC;
DELETE FROM WEBSERV_PRES_PRIN_ACTI;
DELETE FROM WEBSERV_PRES_INDI_UNIRS;
DELETE FROM WEBSERV_PRES_MEDI;
DELETE FROM WEBSERV_PRES_PRES;
